"""Many conversations, one copy of the weights.

Docs: https://vedicreader.github.io/urai/broker.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_broker.ipynb.

# %% auto #0
__all__ = ['MAX_FRAME', 'ChatBroker', 'BrokerChat']

# %% ../nbs/10_broker.ipynb #1e4919ce
import json, os, socket, threading
from fastcore.all import Path
from .core import Resp

# %% ../nbs/10_broker.ipynb #cee0e0e4
MAX_FRAME = 1_000_000   #: refuse a request larger than this, before allocating for it

def _send_json(sock, obj):
    data = json.dumps(obj).encode()
    sock.sendall(len(data).to_bytes(4, 'big') + data)

def _recv_json(sock):
    def read(n):
        out = bytearray()
        while len(out) < n:
            if not (part := sock.recv(n - len(out))): raise EOFError
            out.extend(part)
        return bytes(out)
    n = int.from_bytes(read(4), 'big')
    if n > MAX_FRAME: raise ValueError('broker request too large')
    return json.loads(read(n))

# %% ../nbs/10_broker.ipynb #94997169
def _brok_msgs(req):
    "An `open` request's `messages`: a list of strings, checked before the engine sees it."
    msgs = req.get('messages') or []
    if not isinstance(msgs, list) or not all(isinstance(m, str) for m in msgs):
        raise ValueError('invalid conversation')
    return msgs

def _brok_limit(req):
    "A `send` request's `max_output_tokens`: a positive int, or nothing."
    n = req.get('max_output_tokens')
    if n is None: return None
    if isinstance(n, bool) or not isinstance(n, int) or n < 1: raise ValueError('invalid token limit')
    return n

# %% ../nbs/10_broker.ipynb #663c1d4a
class ChatBroker:
    "Serve isolated text chats over a Unix socket, all sharing one local engine."
    def __init__(self, address, chat_cls, engine=None, model_id=None, **engine_kw):
        self.address, self.chat_cls, self.engine = str(address), chat_cls, engine
        self.model_id, self.engine_kw, self._own_engine = model_id, engine_kw, engine is None
        self.lock, self.state_lock = threading.Lock(), threading.Lock()
        self.listener, self.thread = None, None
        self.clients, self.handlers, self.stopping, self._bound = set(), set(), False, False

    def _mk_engine(self):
        "The shared engine from the backend's own `create_engine`."
        mid = {'model_id': self.model_id} if self.model_id is not None else {}
        return self.chat_cls.create_engine(**mid, **self.engine_kw)

    def _shut_engine(self):
        "Release the engine, but only one this broker built itself."
        if self._own_engine and (c := getattr(self.engine, 'close', None)): c(); self.engine = None

    def _free_socket(self):
        "Clear a socket file a dead broker left behind. A live one is never taken over."
        path = Path(self.address)
        if not path.exists(): return
        if not path.is_socket(): raise RuntimeError(f'broker path exists and is not a socket: {self.address}')
        probe = socket.socket(socket.AF_UNIX)
        try: probe.connect(self.address)
        except ConnectionRefusedError: path.unlink()
        else: raise RuntimeError(f'broker already running at {self.address}')
        finally: probe.close()

    def start(self):
        "Build the engine if this broker owns one, then serve `address` until `close`."
        with self.state_lock:
            if self.listener is not None: return self
            self._free_socket(); listener = None
            try:
                if self.engine is None: self.engine = self._mk_engine()
                listener = socket.socket(socket.AF_UNIX)
                listener.bind(self.address)
                os.chmod(self.address, 0o600)   # this socket drives a model: its owner, nobody else
                listener.listen()
            except Exception:
                if listener is not None: listener.close()
                self._shut_engine(); Path(self.address).unlink(missing_ok=True)
                raise
            self.stopping, self.listener, self._bound = False, listener, True
            self.thread = threading.Thread(target=self._serve, args=(listener,), daemon=True)
            self.thread.start()
        return self

    def _serve(self, listener):
        "Accept clients until the listener closes, one handler thread each."
        while True:
            try: conn, _ = listener.accept()
            except OSError: break
            handler = threading.Thread(target=self._handle, args=(conn,), daemon=True)
            with self.state_lock:
                if self.stopping: conn.close(); break
                self.clients.add(conn); self.handlers.add(handler)
            handler.start()

    def _handle(self, conn):
        "One client: `open` its chat, run `send` turns through it, drop it on `close`."
        chat = None
        try:
            while not self.stopping:
                req = _recv_json(conn)
                if not isinstance(req, dict) or (op := req.get('op')) not in {'open', 'send', 'close'}:
                    raise ValueError('invalid broker request')
                if op == 'open':
                    if chat is not None: raise ValueError('conversation already open')
                    msgs = _brok_msgs(req)
                    with self.lock:
                        chat = self.chat_cls(engine=self.engine, messages=msgs, tools=())
                    _send_json(conn, {'ok': True})
                elif op == 'send':
                    if chat is None or not isinstance(req.get('msg'), str):
                        raise ValueError('invalid message')
                    limit = _brok_limit(req)
                    with self.lock: res = chat(req['msg'], max_output_tokens=limit)
                    _send_json(conn, {'response': res})
                else: _send_json(conn, {'ok': True}); break
        except (EOFError, OSError): pass
        except Exception as e:
            try: _send_json(conn, {'error': f'{type(e).__name__}: {e}'})
            except OSError: pass
        finally:
            if chat is not None:
                with self.lock: chat.close()
            conn.close()
            with self.state_lock:
                self.clients.discard(conn); self.handlers.discard(threading.current_thread())

    def _wake(self):
        """Connect once to wake `accept`, which closing the listener alone may not wake."""
        s = socket.socket(socket.AF_UNIX)
        try: s.connect(self.address)
        except OSError: pass
        finally: s.close()

    @staticmethod
    def _drop(conn):
        "Close a client connection and wake its handler. `close` alone does not wake a blocked `recv`."
        for f in (lambda: conn.shutdown(socket.SHUT_RDWR), conn.close):
            try: f()
            except OSError: pass

    def close(self, timeout=5):
        "Stop serving, drop every client, and release the engine this broker built."
        with self.state_lock:
            listener, thread, handlers = self.listener, self.thread, list(self.handlers)
            clients, bound = list(self.clients), self._bound
            self.stopping, self.listener, self.thread, self._bound = True, None, None, False
        if listener is not None: self._wake(); listener.close()
        for conn in clients: self._drop(conn)
        for t in [thread, *handlers]:
            # a handler wedged inside a turn must not hold shutdown up for ever
            if t is not None and t is not threading.current_thread(): t.join(timeout)
        with self.lock: self._shut_engine()
        if bound: Path(self.address).unlink(missing_ok=True)   # never a socket it did not bind

    def __enter__(self): return self.start()
    def __exit__(self, *a): self.close()

# %% ../nbs/10_broker.ipynb #9e3e7fd1
class BrokerChat:
    "One isolated conversation on a `ChatBroker`: strings out, a `Resp` back."
    def __init__(self, address, messages=None):
        messages = list(messages or [])
        if not all(isinstance(m, str) for m in messages):
            raise TypeError('broker messages must be strings')
        self.conn, self.lock = socket.socket(socket.AF_UNIX), threading.Lock()
        try:
            self.conn.connect(str(address))
            self._call({'op': 'open', 'messages': messages})
        except Exception: self.conn.close(); raise

    def _call(self, req):
        _send_json(self.conn, req); res = _recv_json(self.conn)
        if 'error' in res: raise RuntimeError(res['error'])
        return res

    def __call__(self, msg, max_output_tokens=None):
        "Send one turn through the shared engine."
        if not isinstance(msg, str): raise TypeError('broker messages must be strings')
        with self.lock:
            return Resp(self._call({'op': 'send', 'msg': msg,
                                    'max_output_tokens': max_output_tokens})['response'])

    def close(self):
        "Let the broker drop this conversation. Idempotent."
        with self.lock:
            if getattr(self, 'conn', None) is None: return
            try: self._call({'op': 'close'})
            except (OSError, EOFError): pass
            self.conn.close(); self.conn = None

    def __enter__(self): return self
    def __exit__(self, *a): self.close()
