"""What a model takes and what it hands back, without loading it.

Docs: https://vedicreader.github.io/urai/caps.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_caps.ipynb.

# %% auto #0
__all__ = ['MODALITIES', 'ENDPOINT_TOOLS', 'CAPS_FALLBACK', 'DFLT_CTX', 'MODEL_EXTS', 'Caps', 'tool_modalities', 'tbl_caps',
           'fallback_caps', 'hosted_caps', 'hosted_ctx', 'is_path', 'hub_files', 'mmproj_caps', 'read_cfg', 'cfg_caps']

# %% ../nbs/03_caps.ipynb #6e596c21
import json
from dataclasses import dataclass
from fastcore.all import Path, first

# %% ../nbs/03_caps.ipynb #9e42c4b3
MODALITIES = ('text', 'image', 'audio', 'video')   #: in the spelling fastllm's table uses

@dataclass(frozen=True)
class Caps:
    "What a model can be sent, and what it can send back."
    inp: tuple = ('text',)      # modalities it accepts
    out: tuple = ('text',)      # modalities it returns unprompted
    tools: tuple = ()           # modalities it returns when given a server-side generation tool
    source: str = 'default'     # who answered: fastllm|mmproj|config|runtime|fallback|default

    @property
    def gen_image(self): return 'image' in self.out or 'image' in self.tools
    @property
    def gen_video(self): return 'video' in self.out or 'video' in self.tools
    @property
    def known(self):
        "Did anything actually answer? `default` means nobody knew, not that the model is text-only."
        return self.source != 'default'
    def accepts(self, kind): return kind in self.inp

    def fmt(self):
        "One line for a status bar, silent about a plain text-in, text-out model."
        if not self.known: return 'modalities unknown'
        bits = []
        if self.inp != ('text',): bits.append('in: ' + ' '.join(self.inp))
        if self.out != ('text',): bits.append('out: ' + ' '.join(self.out))
        if self.tools: bits.append('via tool: ' + ' '.join(self.tools))
        return ' · '.join(bits)

    def __repr__(self):
        t = f", tools={'+'.join(self.tools)}" if self.tools else ''
        return f"Caps(in={'+'.join(self.inp)}, out={'+'.join(self.out)}{t}, {self.source})"

# %% ../nbs/03_caps.ipynb #2fa40419
#: `mode` values that describe a generator rather than a chat, and what they return.
_gen_modes = {'image_generation': ('image',), 'video_generation': ('video',), 'audio_speech': ('audio',)}

#: Server-side generation tools, by the endpoint that offers them and what they produce.
ENDPOINT_TOOLS = {'/v1/responses': ('image',)}

def tool_modalities(info):
    "What a model generates when handed a server-side tool, which `supported_output_modalities` never says."
    eps = info.get('supported_endpoints') or ()
    return tuple(dict.fromkeys(m for e, ms in ENDPOINT_TOOLS.items() if e in eps for m in ms))

def tbl_caps(model):
    "Modalities from fastllm's bundled model table, or `None` when it says nothing."
    try:
        from fastllm.types import get_model_info
        v, _, m = str(model).partition('/')
        info = get_model_info(m or v, v if m else None) or {}
    except Exception: return None
    inp, out = info.get('supported_modalities'), info.get('supported_output_modalities')
    out = tuple(out) if out else _gen_modes.get(info.get('mode'))
    if not inp: inp = ('text', 'image') if info.get('supports_vision') else None
    if not inp and not out: return None
    return Caps(tuple(inp or ('text',)), tuple(out or ('text',)), tool_modalities(info), 'fastllm')

# %% ../nbs/03_caps.ipynb #97e97ac3
#: Modalities for vendors fastllm's table leaves blank. Prefix -> (inp, out).
CAPS_FALLBACK = {p: (('text', 'image'), ('text',)) for p in
                 ('claude', 'anthropic/', 'sonnet', 'opus', 'haiku', 'fable')}

def fallback_caps(model):
    "Modalities from `CAPS_FALLBACK`, for the vendors fastllm's table leaves empty."
    s = str(model).lower()
    hit = first(CAPS_FALLBACK.items(), lambda kv: kv[0] in s)
    return Caps(hit[1][0], hit[1][1], (), 'fallback') if hit else None

def hosted_caps(model):
    "Best answer for a hosted model: the table, then the name, then nothing."
    return tbl_caps(model) or fallback_caps(model) or Caps()

# %% ../nbs/03_caps.ipynb #658be19c
DFLT_CTX = 128_000   #: assumed when nothing knows better

def hosted_ctx(model, dflt=DFLT_CTX):
    "Context window for a hosted model, as `(tokens, note)`. The note says so when it was a guess."
    try:
        from fastllm.types import get_model_info
        v, _, m = str(model).partition('/')
        info = get_model_info(m or v, v if m else None) or {}
        if (n := info.get('max_input_tokens') or info.get('max_tokens')): return int(n), ''
    except Exception as e: return dflt, f'context window unknown ({type(e).__name__}), assuming {dflt//1000}k'
    return dflt, f'context window unknown, assuming {dflt//1000}k'

# %% ../nbs/03_caps.ipynb #0e521724
MODEL_EXTS = ('.gguf', '.litertlm')   #: file suffixes that mean "a model, not a repo id"

def is_path(model):
    "Does `model` name a local file rather than a hub repo id?"
    return bool(model) and (str(model).lower().endswith(MODEL_EXTS) or Path(model).exists())

def hub_files(repo):
    "Every already-cached file path for hub repo `repo`. Never touches the network."
    try:
        from huggingface_hub import scan_cache_dir
        r = first(scan_cache_dir().repos, lambda r: r.repo_id == str(repo))
    except Exception: return []
    return [str(f.file_path) for rev in r.revisions for f in rev.files] if r else []

def mmproj_caps(model, model_path=None):
    "A GGUF model with an `mmproj` projector beside it takes images."
    fs = list(hub_files(model)) if model and not is_path(model) else []
    for p in (model_path, model):
        d = Path(p).parent if p else None
        if d and d.is_dir(): fs += [str(x) for x in d.glob('*.gguf')]
    if any('mmproj' in Path(f).name.lower() for f in fs):
        return Caps(('text', 'image'), ('text',), (), 'mmproj')
    return None

# %% ../nbs/03_caps.ipynb #5eb5f36a
#: `config.json` keys that mark a second tower, by the modality it reads.
_tower_keys = {'image': ('vision_config', 'vision_tower', 'image_token_index'),
               'audio': ('audio_config',)}

def read_cfg(model, model_path=None):
    "A model's `config.json` as a dict, from a local directory or the hub cache, else `{}`."
    for p in (model_path, model):
        if p and (f := Path(p)/'config.json').exists():
            try: return json.loads(f.read_text())
            except Exception: pass
    try:
        from huggingface_hub import hf_hub_download
        return json.loads(Path(hf_hub_download(str(model), 'config.json',
                                               local_files_only=True)).read_text())
    except Exception: return {}

def cfg_caps(model, model_path=None):
    "Modalities a model's `config.json` declares, from the towers it carries beside the text one."
    cfg = read_cfg(model, model_path)
    if not cfg: return None
    inp = ('text',) + tuple(k for k, ks in _tower_keys.items() if any(x in cfg for x in ks))
    return Caps(inp, ('text',), (), 'config')
