"""One conversation across any backend.

Docs: https://vedicreader.github.io/urai/chat.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_chat.ipynb.

# %% auto #0
__all__ = ['budget_msg_', 'cancel_msg_', 'cancelled_reply_', 'ContextWindowExceededError', 'is_ctx_error', 'get_runtime', 'Chat',
           'mk_chat', 'AsyncChat', 'adisplay_stream', 'ask_console', 'http_approval', 'hitl_policy']

# %% ../nbs/05_chat.ipynb #0d7e6a32
import asyncio, json, os, threading
from urllib.request import Request, urlopen
from dataclasses import replace
from fastcore.all import L, GetAttr, SaveReturn, asave_iter, patch
from .core import UsageStats, Resp, resp_text, run_cbs
from .msgs import mk_content, mk_msg, mk_msgs, is_media
from .opts import (RUNTIMES, ChatOpts, ModelSpec, split_runtime, resolve_runtime,
                       load_ref, set_dotted, turn_kw)

# %% ../nbs/05_chat.ipynb #4945c4d3
budget_msg_ = 'Tool-call budget exceeded; no more tools will run this turn.'
cancel_msg_ = 'Not run: the user stopped this turn.'
cancelled_reply_ = '(stopped by the user)'

class ContextWindowExceededError(RuntimeError):
    "A turn could not finish: the context window filled and recovery also failed."

_ctx_err_markers = ('context window', 'context length', 'max number of tokens', 'out of bounds',
                    'kv cache', 'n_ctx', 'exceed context', 'available state entries')

def is_ctx_error(chat, e):
    "Best effort: does `e`, from a backend step, look like the context window filling up?"
    if any(m in str(e).lower() for m in _ctx_err_markers): return True
    try: return bool(chat.ctx_limit) and chat.pct_full >= 1
    except Exception: return False

# %% ../nbs/05_chat.ipynb #63496152
def get_runtime(nm):
    "The `Chat` subclass for runtime `nm`, importing the backend module lazily."
    rt = RUNTIMES[nm]
    try: return load_ref(rt.cls)
    except ImportError as e:
        if not rt.optional: raise
        raise ImportError(f'The {nm!r} runtime is unavailable ({e}). '
                          f'Install it with: {rt.install}') from None

# %% ../nbs/05_chat.ipynb #eebcf0ec
class Chat:
    "Backend-agnostic chat. `Chat(model)` returns the subclass for that model's runtime."
    _runtime = None          # the registry name this subclass serves
    _opt_map = {}            # portable option name -> this backend's own (dotted nests)
    _opt_skip = ()           # ...and the ones it cannot honour at all
    _dflt_cbs = []
    _stream_raw = False      # `stream='raw'` yields chunk dicts instead of markdown
    _media_ok = True         # can this transport carry pictures and sound?
    _media_note = ''         # ...and if not, what to use instead

    def __new__(cls, model=None, *, runtime=None, model_path=None, **kw):
        if cls is not Chat: return super().__new__(cls)
        nm, _ = resolve_runtime(model, runtime, model_path)
        sub = get_runtime(nm)
        # through the subclass's own `__new__`, not `object.__new__`: a backend may re-route
        # again (an MLX vision repo picks a different class)
        return sub.__new__(sub, model, runtime=runtime, model_path=model_path, **kw)

    def __init__(self, model=None, *, runtime=None, model_path=None, opts=None, **kw):
        self._setup(model, ChatOpts.create(opts, **kw))

    def _setup(self, model=None, opts=None):
        "Initialize shared chat state."
        _, model = split_runtime(model)
        o = self.opts = ChatOpts.create(opts)
        if o.max_parallel_tools and o.max_parallel_tools < 1:
            raise ValueError('max_parallel_tools must be at least 1')
        self.tools = L(o.tools)
        self.hist = self.fmt2hist(o.messages)
        self.use, self.cbs, self.turn_msg, self.turn_res = UsageStats(), L(), None, None
        self._steps, self._budget_exceeded, self._final_sent = 0, False, False
        self._cancel = threading.Event()
        if o.default_cbs: self.add_cbs(self._dflt_cbs)
        self.add_cbs(o.cbs)
        return model

    mk_content, mk_msg, mk_msgs = staticmethod(mk_content), staticmethod(mk_msg), staticmethod(mk_msgs)

    def fmt2hist(self, msgs):
        "Backend messages -> canonical urai history dicts. Backends override; the base normalizes."
        return self.mk_msgs(msgs)

    @property
    def runtime(self): return self._runtime
    @property
    def pct_full(self): return self.token_count / self.ctx_limit
    @property
    def cancelled(self): return self._cancel.is_set()

    def map_opts(self, kw):
        "Portable option names under this backend's own, dropping what it cannot honour."
        out = {}
        for k, v in (kw or {}).items():
            if k in self._opt_skip: continue
            set_dotted(out, self._opt_map.get(k, k), v)
        return out

# %% ../nbs/05_chat.ipynb #4aaae736
#: Options common enough to deserve an attribute of their own.
_OPT_ATTRS = ('sp', 'approve', 'max_steps', 'tool_max_len', 'parallel_tools',
              'max_parallel_tools', 'final_prompt', 'ctx')

def _opt_prop(name):
    return property(lambda self: getattr(self.opts, name),
                    lambda self, v: setattr(self, 'opts', replace(self.opts, **{name: v})))

for _n in _OPT_ATTRS: setattr(Chat, _n, _opt_prop(_n))

# %% ../nbs/05_chat.ipynb #cb3b5448
@patch
def add_cb(self:Chat, cb):
    "Register a callback, class or instance. Binds `cb.chat` and returns the instance."
    if isinstance(cb, type): cb = cb()
    cb.chat = self; self.cbs.append(cb); return cb

@patch
def add_cbs(self:Chat, cbs):
    "Register several callbacks and return the `L` of registered instances."
    return L(cbs).map(self.add_cb)

@patch
def remove_cb(self:Chat, cb):
    "Remove a callback by instance, or by class to drop every callback of that type."
    keep = (lambda c: not isinstance(c, cb)) if isinstance(cb, type) else (lambda c: c is not cb)
    self.cbs = self.cbs.filter(keep); return self

@patch
def remove_cbs(self:Chat, cbs):
    "Remove several callbacks, by instance or by class."
    L(cbs).map(self.remove_cb); return self

# %% ../nbs/05_chat.ipynb #ce88eb0f
@patch
def __call__(self:Chat, msg=None, stream=False, cbs=None, **kw):
    """Run one chat turn.

    `stream=True` yields markdown. `stream='raw'` yields chunk dicts. Keyword options apply
    only to this turn. One `Chat` instance is mutable and not safe for concurrent turns."""
    self.use, self._steps, self._budget_exceeded, self._final_sent = UsageStats(), 0, False, False
    self._cancel.clear()
    self._stream_raw = stream == 'raw'
    kw = turn_kw(**kw)
    if stream: return self._stream_turn(msg, cbs, **kw)
    added = self.add_cbs(cbs)
    try:
        r = self._send(msg, **kw)
        if self._budget_exceeded and not self._final_sent:
            self._final_sent = True
            r = self._send(self.final_prompt, **kw)
        return r
    finally: self.remove_cbs(added)

@patch
def _stream_turn(self:Chat, msg, cbs=None, **kw):
    "Stream one turn, plus a `final_prompt` round if the tool-call budget ended it early."
    r = yield from self._stream(msg, cbs, **kw)
    if self._budget_exceeded and not self._final_sent:
        self._final_sent = True
        r = yield from self._stream(self.final_prompt, cbs, **kw)
    return r

@patch
def _emit(self:Chat, o, fmt):
    "One streamed chunk: the raw dict in raw mode, else `fmt`-rendered markdown."
    return o if self._stream_raw else fmt.format_item(o)

@patch
def _check_media(self:Chat):
    "Refuse media a text-only transport cannot carry, rather than dropping it in silence."
    if self._media_ok: return
    c = (self.turn_msg or {}).get('content')
    if isinstance(c, list) and any(is_media(p) for p in c): raise TypeError(self._media_note)

# %% ../nbs/05_chat.ipynb #d7702244
@patch
def _recreate_conv(self:Chat):
    "Rebuild backend conversation state from `self.hist`."
    pass

@patch
def _set_sp(self:Chat, sp):
    "Note a new system prompt wherever the backend keeps one. `_recreate_conv` applies it."
    pass

@patch
def _set_tools(self:Chat, tools):
    "Rebuild whatever tool state the backend holds: wire schemas, a call namespace."
    pass

@patch
def reconfigure(self:Chat, sp=None, tools=None):
    "Change `sp` or `tools` while keeping `hist`; `None` preserves a value and `tools=()` clears tools."
    if sp is not None: self.sp = sp; self._set_sp(sp)
    if tools is not None:
        self.opts = replace(self.opts, tools=tuple(L(tools)))
        self.tools = L(tools); self._set_tools(self.tools)
    self._recreate_conv()
    return self

# %% ../nbs/05_chat.ipynb #26a93710
@patch
def cancel(self:Chat):
    "Ask the turn in flight to stop at its next safe point. Safe to call from another thread."
    self._cancel.set()
    return True

@patch
def oneshot(self:Chat, prompt, sp='', think=None, max_tokens=None):
    "Return one stateless reply without tools or history; `think=False` disables deliberation."
    return self._oneshot(prompt, sp, think=think, max_tokens=max_tokens)

@patch
def _oneshot(self:Chat, prompt, sp='', think=None, max_tokens=None):
    "One stateless completion's text. Every backend implements it; `oneshot` is the public door."
    raise NotImplementedError

@patch
def recover_context(self:Chat, error, max_output_tokens=None):
    "Backend contract for recovering from a full context window."
    raise ContextWindowExceededError(
        f'context recovery is not implemented for {type(self).__name__}') from error

@patch
def close(self:Chat):
    "Release backend resources. Overridden per backend."
    pass

@patch
def __del__(self:Chat):
    try: self.close()
    except Exception: pass

@patch
def print_hist(self:Chat):
    "Render the conversation history as markdown, or plain text outside a notebook."
    md = '\n\n---\n\n'.join(f"**{m.get('role','?')}**\n\n{Resp(m)._repr_markdown_()}"
                            for m in self.hist)
    try:
        from IPython.display import Markdown, display
        display(Markdown(md))
    except Exception: print(md)

# %% ../nbs/05_chat.ipynb #f1deb121
def mk_chat(model=None, opts=None, *, runtime=None, model_path=None, **kw):
    "Build a `Chat`. `model` is a name, a `ModelSpec`, or nothing for the default runtime."
    if isinstance(model, ModelSpec):
        spec = model
        model, runtime = spec.model_id, spec.runtime
        kw = {'ctx': spec.ctx, **spec.opts, **kw}
    return Chat(model, runtime=runtime, model_path=model_path, opts=ChatOpts.create(opts, **kw))

# %% ../nbs/05_chat.ipynb #7a327050
class AsyncChat(GetAttr):
    "Async twin of `Chat`. Blocking calls run in a worker thread."
    _default = 'chat'
    def __init__(self, model=None, *, runtime=None, **kw):
        self.chat = model if hasattr(model, '_send') else Chat(model, runtime=runtime, **kw)

    async def __call__(self, msg=None, stream=False, cbs=None, **kw):
        "Run one chat turn. `await` the result, or an async chunk iterator when `stream` is set."
        if stream: return self._astream(msg, cbs, **kw)
        return await asyncio.to_thread(lambda: self.chat(msg, False, cbs, **kw))

    @asave_iter
    async def _astream(it, self, msg, cbs=None, **kw):
        "Drive the sync stream in a worker thread. The iterator's `.value` holds the final `Resp`."
        g = SaveReturn(self.chat(msg, stream=True, cbs=cbs, **kw))
        gi, done = iter(g), object()
        while (o := await asyncio.to_thread(next, gi, done)) is not done: yield o
        it.value = g.value

    def close(self): self.chat.close()
    async def __aenter__(self): return self
    async def __aexit__(self, *exc): self.close()

async def adisplay_stream(chunks):
    "Async twin of `display_stream`. Renders live in a notebook, and returns the full markdown."
    if not hasattr(chunks, '__aiter__'): chunks = await chunks
    from IPython.display import display, Markdown
    h, md = display(Markdown(''), display_id=True), ''
    async for c in chunks:
        md += c
        if h is not None: h.update(Markdown(md))
    return md

# %% ../nbs/05_chat.ipynb #dc47c321
def ask_console(tc):
    "Console y/N approval prompt for a tool call."
    a = tc['function'].get('arguments', {})
    return input(f"Authorize {tc['function']['name']}({a})? [y/N] ").strip().lower() in ('y', 'yes')

def http_approval(url=None, timeout=300):
    "An approval callback that asks a running web UI over HTTP."
    endpoint = (url or os.environ.get('URAI_APPROVAL_URL')
                or 'http://127.0.0.1:5001').rstrip('/') + '/agent/approval/request'
    def ask(tc):
        body = json.dumps({'tool_call': tc, 'timeout': timeout}).encode()
        req = Request(endpoint, data=body, headers={'Content-Type': 'application/json'},
                      method='POST')
        try:
            with urlopen(req, timeout=timeout + 5) as res: reply = json.load(res)
        except Exception as e:
            raise RuntimeError(f'approval request failed at {endpoint}: {e}') from e
        return bool(reply.get('answer', {}).get('answer'))
    return ask

def hitl_policy(modes, ask=None, http=False):
    "An `approve(tool_call)` from per-tool modes. `http` asks a web UI instead of the console."
    ask = http_approval(http if isinstance(http, str) else None) if http else (ask or ask_console)
    def approve(tc):
        mode = modes.get(tc['function']['name'], 'check') if modes else 'check'
        return True if mode == 'approved' else False if mode == 'dont_run' else ask(tc)
    return approve
