"""Usage counting, callbacks, and response rendering.

Docs: https://vedicreader.github.io/urai/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['system_certs', 'tool_reminder_', 'use_system_certs', 'UsageStats', 'ChatCallback', 'run_cbs', 'resp_text', 'thought',
           'truncated', 'has_tool_call', 'quote_', 'tc_summary_', 'mk_tr_details', 'Resp', 'StreamFormatter',
           'display_stream', 'TruncationCallback']

# %% ../nbs/00_core.ipynb #a7a01fd9
import json, os
from html import escape
from fastcore.all import store_attr, GetAttr, L

# %% ../nbs/00_core.ipynb #846c8e36
def use_system_certs(force=False):
    "Use the OS trust store. Return false when unavailable or disabled by `URAI_SYSTEM_CERTS=0`."
    off = os.getenv('URAI_SYSTEM_CERTS', os.getenv('RISHI_SYSTEM_CERTS', '1')) == '0'
    if not force and off: return False
    try: import truststore
    except ImportError: return False
    truststore.inject_into_ssl()    # idempotent: it rebinds `ssl.SSLContext` to its own
    return True

system_certs = use_system_certs()   #: done once, on import

# %% ../nbs/00_core.ipynb #46e5f751
class UsageStats:
    "Token usage for one chat turn."
    _sums = ('prompt_tokens', 'completion_tokens', 'total_tokens', 'n', 'cached_tokens', 'cost',
             'reasoning_tokens', 'cache_creation_tokens')
    def __init__(self,
                 prompt_tokens=0,           # tokens in the prompt
                 completion_tokens=0,       # tokens the model generated
                 total_tokens=0,            # prompt + completion, as the backend reports it
                 n=0,                       # turns folded into this total
                 cached_tokens=0,           # prompt tokens served from a KV or prefix cache
                 cost=0.0,                  # what the provider charged; 0 for local inference
                 model=None,                # which model spent them
                 reasoning_tokens=0,        # billed separately by hosted providers
                 cache_creation_tokens=0):  # ...as are cache writes
        store_attr()

    def __add__(self, other):
        if other is None: return self
        return UsageStats(**{k: getattr(self, k) + getattr(other, k) for k in self._sums},
                          model=self.model or other.model)
    def __radd__(self, other): return self if other in (None, 0) else self.__add__(other)

    def __repr__(self):
        p = [f'total={self.total_tokens:,}', f'in={self.prompt_tokens:,}',
             f'out={self.completion_tokens:,}', f'turns={self.n}']
        for k, lbl in (('cached_tokens','cached'), ('reasoning_tokens','reasoning'),
                       ('cache_creation_tokens','cache_write')):
            if (v := getattr(self, k)): p.append(f'{lbl}={v:,}')
        if self.cost: p.append(f'cost=${self.cost:,.4f}')
        if self.model: p.append(f'model={self.model}')
        return '|'.join(p)

    def fmt(self):
        "Markdown `<details>` token block, empty when nothing was spent."
        if not self.total_tokens: return ''
        return f"\n\n<details><summary>{self.total_tokens:,} tokens</summary>\n\n`{self!r}`\n\n</details>\n"

# %% ../nbs/00_core.ipynb #19d8025c
class ChatCallback(GetAttr):
    "Base chat callback. Reads chat state via `GetAttr`, so `self.turn_msg` is `chat.turn_msg`."
    order, _default, chat, run = 0, 'chat', None, True
    def __repr__(self): return type(self).__name__

def run_cbs(chat, event):
    "Dispatch `event` to enabled callbacks in `order`, forwarding whatever they yield."
    for cb in chat.cbs.sorted('order'):
        if cb.run and hasattr(cb, event):
            r = getattr(cb, event)()
            if r is not None: yield from r

# %% ../nbs/00_core.ipynb #98358cab
def resp_text(resp):
    "The text of a response or chunk dict, whichever content shape it uses."
    c = resp.get('content', []) if isinstance(resp, dict) else ''
    if isinstance(c, str): return c
    return ''.join(p.get('text', '') for p in c if isinstance(p, dict) and p.get('type') == 'text')

def thought(resp):
    "The model's thinking (`channels.thought`), or ''."
    return resp.get('channels', {}).get('thought', '') if isinstance(resp, dict) else ''

def truncated(resp):
    "Was `resp` flagged as cut off at the token cap?"
    return bool(resp.get('truncated')) if isinstance(resp, dict) else False

def has_tool_call(o):
    "Does this chunk carry a `tool_call` content part?"
    return any(isinstance(p, dict) and p.get('type') == 'tool_call'
               for p in (o.get('content') or [] if isinstance(o, dict) else []))

# %% ../nbs/00_core.ipynb #eeaab263
def quote_(text):
    "`text` as a markdown blockquote under a Thinking header."
    return '> **🧠 Thinking**\n>\n' + '\n'.join('> ' + l for l in text.splitlines())

def tc_summary_(name, args, result=None):
    "One-line `<code>` summary of a tool call."
    params = ', '.join(f'{k}={v!r}' for k, v in (args or {}).items())
    res = f' -> {result}' if result is not None else ''
    return '<code>' + escape(f'{name}({params}){res}') + '</code>'

def mk_tr_details(name, args, result, mx=2000):
    "`<details>` JSON block for a completed tool call."
    body = json.dumps({'call': {'function': name, 'arguments': args}, 'result': str(result)[:mx]}, indent=2)
    return (f'\n\n<details><summary>{tc_summary_(name, args, result)}</summary>\n\n'
            f'```json\n{body}\n```\n\n</details>\n\n')

class Resp(dict):
    "A response dict that renders as markdown in a notebook."
    def _repr_markdown_(self):
        md = ''
        if th := thought(self): md += quote_(th) + '\n\n'
        md += resp_text(self)
        for tc in self.get('tool_calls', []):
            fn = tc.get('function', {})
            md += f"\n\n🔧 {fn.get('name','')}({fn.get('arguments', {})})"
        for p in (self.get('content') or []):
            if isinstance(p, dict) and p.get('type') == 'tool_response':
                md += f"\n\n↩︎ **{p.get('name','')}**: {p.get('response')}"
        return md or '*(no text)*'

# %% ../nbs/00_core.ipynb #237852b7
class StreamFormatter:
    "Format a chunk stream to markdown. Thinking streams as one blockquote."
    def __init__(self, mx=2000, showthink=True, showcalls=False):
        self.outp = ''; self._inthink = False; store_attr()

    def format_item(self, o):
        "Format one chunk dict: thinking, text, or a tool call."
        res = ''
        if (th := thought(o)) and self.showthink:
            if not self._inthink: res += '> **🧠 Thinking**\n>\n> '; self._inthink = True
            res += th.replace('\n', '\n> ')
        if txt := resp_text(o):
            if self._inthink: res += '\n\n'; self._inthink = False
            res += txt
        if self.showcalls:
            for p in (o.get('content', []) if isinstance(o, dict) else []):
                if isinstance(p, dict) and p.get('type') == 'tool_call':
                    res += f"\n- ⏳ {tc_summary_(p.get('name', ''), p.get('arguments', {}))}\n"
        self.outp += res
        return res

    def format_stream(self, rs):
        "Yield markdown for each chunk, closing any open thinking blockquote at the end."
        for o in rs: yield self.format_item(o)
        if self._inthink: self._inthink = False; yield '\n\n'

def display_stream(chunks):
    "Render a markdown-chunk stream live in a notebook, and return the full markdown."
    from IPython.display import display, Markdown
    h, md = display(Markdown(''), display_id=True), ''
    for c in chunks:
        md += c
        if h is not None: h.update(Markdown(md))
    return md

# %% ../nbs/00_core.ipynb #f21653a2
tool_reminder_ = ('\n<system-reminder>After every tool call result, briefly summarise in prose '
                  'what you found before continuing or calling another tool.</system-reminder>')

class TruncationCallback(ChatCallback):
    "Flag a reply that reaches the output cap when usage data is available."
    order = 20
    def __init__(self, max_tokens): store_attr()
    def after_response(self):
        if self.chat.use.completion_tokens >= self.max_tokens: self.chat.turn_res['truncated'] = True
