"""Running the tools a model asks for, and keeping the window from filling.

Docs: https://vedicreader.github.io/urai/loop.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_loop.ipynb.

# %% auto #0
__all__ = ['UsageCallback', 'ToolReminderCallback', 'ToolLoopMixin', 'msg_groups', 'evict_middle', 'SlidingWindowCallback']

# %% ../nbs/06_loop.ipynb #46cae8e7
from concurrent.futures import ThreadPoolExecutor
from fastcore.funccall import mk_ns, call_func
from fastcore.all import L, store_attr, patch
from .core import (UsageStats, ChatCallback, StreamFormatter, Resp, run_cbs, resp_text,
                       thought, has_tool_call, tool_reminder_)
from .msgs import mk_msg, mk_toolspec, tc_name, mk_tool_res_msg, sum_usage
from .chat import (Chat, ContextWindowExceededError, is_ctx_error,
                       budget_msg_, cancel_msg_, cancelled_reply_)

# %% ../nbs/06_loop.ipynb #eff0a0a6
class UsageCallback(ChatCallback):
    "Fold each turn's `usage` block, summed across tool rounds, into `chat.use`."
    order = 10
    def after_response(self):
        u = self.chat.turn_res.get('usage') or {}
        self.chat.use += UsageStats(
            u.get('prompt_tokens', 0), u.get('completion_tokens', 0), u.get('total_tokens', 0), 1,
            cached_tokens=u.get('cached_tokens', 0), model=u.get('model'),
            reasoning_tokens=u.get('reasoning_tokens', 0),
            cache_creation_tokens=u.get('cache_creation_tokens', 0), cost=u.get('cost', 0.0))

class ToolReminderCallback(ChatCallback):
    "Ask the model to say what a tool result told it, rather than silently calling the next one."
    order = 30
    def __init__(self, tool_reminder=tool_reminder_): store_attr()
    def before_send(self):
        m = self.chat.turn_msg
        if not self.chat.tools or m is None: return
        if isinstance(m.get('content'), str): m['content'] += self.tool_reminder
        elif isinstance(m.get('content'), list):
            m['content'].append({'type': 'text', 'text': self.tool_reminder})

# %% ../nbs/06_loop.ipynb #098b3266
class ToolLoopMixin:
    "The Python-side tool loop, for backends that get tool calls back as data."
    _ctx_tokens = 0

    def _set_tools(self, tools):
        "Rebuild the wire schemas and the call namespace."
        self.toolspecs = [mk_toolspec(t) for t in L(tools)]
        self.ns = mk_ns([t for t in L(tools) if callable(t)])

    def call_tool(self, tc):
        "Run one approved call against `self.ns`. An exception comes back as an error string."
        if tc.get('server'): return '(run by the provider)'   # the provider's to run, not ours
        try: return call_func(tc_name(tc), (tc.get('function') or {}).get('arguments') or {}, ns=self.ns)
        except Exception as e: return f'{type(e).__name__}: {e}'

    def _approve1(self, tc):
        "Fire `before_tool_calls`, then check `tc` against approval and the tool-call budget."
        self.turn_tc = tc
        for _ in run_cbs(self, 'before_tool_calls'): pass
        over = self._budget_exceeded or (self.max_steps is not None and self._steps >= self.max_steps)
        ok = False if over else (self.approve is None or self.approve(tc))
        if ok: self._steps += 1
        else: self._budget_exceeded = self._budget_exceeded or over
        return ok, (budget_msg_ if over else 'Denied by human operator')

    def _record_tool(self, tc, out):
        "Truncate an over-long result, record it in `hist`, and fire `after_tool_calls`."
        # measured on the string the model will see, not on the object: a tool returning a
        # huge list costs the same context as one returning a huge string
        if self.tool_max_len and len(s := out if isinstance(out, str) else str(out)) > self.tool_max_len:
            out = s[:self.tool_max_len] + ' ...[truncated]'
        self.turn_tc, self.turn_tool_result = tc, out
        self.hist.append(mk_tool_res_msg(tc, out))
        for _ in run_cbs(self, 'after_tool_calls'): pass

    def _run_tools(self, res):
        "Approve every call first, then run the approved ones, in parallel where that was allowed."
        self.hist.append(res)
        tcs = res.get('tool_calls') or []
        oks = [self._approve1(tc) for tc in tcs]
        todo = [tc for tc, (ok, _) in zip(tcs, oks) if ok]
        allowed = self.parallel_tools
        if not isinstance(allowed, bool): allowed = set(allowed or ())
        can_par = len(todo) > 1 and bool(allowed) and all(allowed is True or tc_name(tc) in allowed
                                                          for tc in todo)
        if can_par:
            n = min(len(todo), self.max_parallel_tools or len(todo))
            with ThreadPoolExecutor(max_workers=n, thread_name_prefix='urai-tool') as ex:
                outs = list(ex.map(self.call_tool, todo))
        else: outs = [cancel_msg_ if self.cancelled else self.call_tool(tc) for tc in todo]
        outs = iter(outs)
        for tc, (ok, denial) in zip(tcs, oks): self._record_tool(tc, next(outs) if ok else denial)

    def _refuse_tools(self, res, why=cancel_msg_):
        "Record `res` and a refusal for each call it proposed, without running any."
        self.hist.append(res)
        for tc in res.get('tool_calls') or []: self._record_tool(tc, why)

    def _cut_res(self, text, thought=''):
        "The assistant message for a turn cut mid-stream."
        res = Resp({'role': 'assistant', 'content': text or cancelled_reply_})
        if thought: res['channels'] = {'thought': thought}
        return res

    def _finish_turn(self, res, us, recorded=False):
        "Shared tail: total the turn's usage and record the response."
        if (u := sum_usage(us)): res['usage'] = u
        if us: self._ctx_tokens = (us[-1] or {}).get('total_tokens', self._ctx_tokens)
        self.turn_res = res
        if not recorded: self.hist.append(res)

# %% ../nbs/06_loop.ipynb #59752641
@patch
def _send(self:ToolLoopMixin, msg, **kw):
    "Send one message, looping until the model stops calling tools or the budget ends the turn."
    self.turn_msg = self.mk_msg(msg)
    self._check_media()
    for _ in run_cbs(self, 'before_send'): pass
    if self.turn_msg is not None: self.hist.append(self.turn_msg)
    us, recorded = [], False
    while True:
        try: res = self._model_step(**kw)
        except Exception as e:
            if not is_ctx_error(self, e): raise
            res = self.recover_context(e, **kw)
        us.append(res.get('usage'))
        if not res.get('tool_calls') or self._budget_exceeded: break
        if self.cancelled: self._refuse_tools(res); recorded = True; break
        self._run_tools(res)
        if self.cancelled: recorded = True; break
        if self._budget_exceeded: break
    self._finish_turn(res, us, recorded)
    for _ in run_cbs(self, 'after_response'): pass
    return self.turn_res

# %% ../nbs/06_loop.ipynb #501ef736
@patch
def recover_context(self:ToolLoopMixin, err, keep_last=4, mx=500, **kw):
    "Window full mid-turn: shrink the oldest tool results, rebuild backend state, and ask for a close."
    idxs = [i for i, m in enumerate(self.hist) if m.get('role') == 'tool']
    for i in (idxs[:-keep_last] if keep_last else idxs):
        c = self.hist[i].get('content')
        if isinstance(c, str) and len(c) > mx:
            self.hist[i]['content'] = c[:mx] + ' ...[truncated to recover context]'
    self._budget_exceeded = self._final_sent = True   # no more tools, and this *is* the final round
    self._recreate_conv()
    self.hist.append(mk_msg(self.final_prompt))
    try: return self._model_step(**kw)
    except Exception:
        raise ContextWindowExceededError(
            f'could not recover after truncating tool results: {err}') from err

# %% ../nbs/06_loop.ipynb #caefbf45
@patch
def _stream(self:ToolLoopMixin, msg, cbs=None, **kw):
    "Stream a turn as markdown chunks. Callbacks in `cbs` live only for this turn."
    added = self.add_cbs(cbs); prev = getattr(self, '_streaming', False); self._streaming = True
    try:
        self.turn_msg = self.mk_msg(msg)
        self._check_media()
        for _ in run_cbs(self, 'before_send'): pass
        if self.turn_msg is not None: self.hist.append(self.turn_msg)
        fmt, us, recorded, cut = StreamFormatter(), [], False, False
        while True:
            said, thought_, announced = [], [], False
            step = self._stream_step(**kw)
            try:
                for o in step:
                    if self.cancelled: cut = True; break
                    said.append(resp_text(o)); thought_.append(thought(o))
                    announced = announced or has_tool_call(o)
                    if (s := self._emit(o, fmt)): yield s
            except Exception as e:
                if not is_ctx_error(self, e): raise
                res = self.recover_context(e, **kw)
                yield self._emit(res, StreamFormatter())
                us.append(res.get('usage')); break
            finally:
                if cut: step.close()
            if fmt._inthink and not self._stream_raw: fmt._inthink = False; yield '\n\n'
            if cut:
                res = self._cut_res(''.join(said), ''.join(thought_))
                self.hist.append(res); recorded = True
                break
            res = self._step_res
            us.append(res.get('usage'))
            if not res.get('tool_calls') or self._budget_exceeded: break
            if not announced:
                for tc in res['tool_calls']:
                    o = {'content': [{'type': 'tool_call', 'name': tc_name(tc),
                                      'arguments': (tc.get('function') or {}).get('arguments', {})}]}
                    if (s := self._emit(o, fmt)): yield s
            if self.cancelled: self._refuse_tools(res); recorded = True; break
            self._run_tools(res)
            if self.cancelled: recorded = True; break
            if self._budget_exceeded: break
        self._finish_turn(res, us, recorded)
        yield from run_cbs(self, 'after_response')
        return self.turn_res    # captured by `SaveReturn` and `AsyncChat`'s `.value`
    finally: self._streaming = prev; self.remove_cbs(added)

# %% ../nbs/06_loop.ipynb #e2129bb4
def msg_groups(hist):
    "Split `hist` into atomic groups: a tool-calling assistant message stays with its results."
    groups, cur = [], []
    for m in hist:
        if m.get('role') == 'tool':
            if cur: cur.append(m); continue
            groups.append([m]); continue         # an orphan result: keep it whole anyway
        if cur: groups.append(cur); cur = []
        if m.get('tool_calls'): cur = [m]
        else: groups.append([m])
    if cur: groups.append(cur)
    return groups

def evict_middle(hist, keep_first=2, keep_last=8):
    "Drop whole groups from the middle of `hist`. Returns `(new_hist, dropped)`."
    groups = msg_groups(hist)
    if len(groups) <= keep_first + keep_last: return list(hist), []
    keep = groups[:keep_first] + (groups[-keep_last:] if keep_last else [])
    drop = groups[keep_first:len(groups) - keep_last] if keep_last else groups[keep_first:]
    return [m for g in keep for m in g], [m for g in drop for m in g]

# %% ../nbs/06_loop.ipynb #fa4b6412
_sum_sp = 'Summarize the conversation extract faithfully and briefly. Reply with the summary only.'

class SlidingWindowCallback(ChatCallback):
    "Evict the middle of `hist` before a turn that would overflow. Needs `chat.ctx_limit` set."
    order = 5
    def __init__(self,
                 threshold=0.9,    # evict once the context is this full
                 keep_first=2,     # leading groups to anchor: the task, usually
                 keep_last=8,      # trailing groups to keep: the live thread
                 summarize=False,  # spend one model call replacing the dropped middle with a summary
                 mx=4000):         # characters of dropped conversation to feed the summarizer
        store_attr()

    def _summary(self, dropped):
        "A stand-in for the dropped middle, or None if the model cannot produce one."
        convo = '\n'.join(f"{m.get('role','?')}: {resp_text(m)}" for m in dropped)[:self.mx]
        try: return self.chat.oneshot(
            f'Summarize this earlier part of a conversation:\n\n{convo}', _sum_sp, think=False)
        except Exception: return None

    def before_send(self):
        c = self.chat
        if not getattr(c, 'ctx_limit', None) or c.pct_full < self.threshold: return
        kept, dropped = evict_middle(c.hist, self.keep_first, self.keep_last)
        if not dropped: return
        if self.summarize and (s := self._summary(dropped)):
            # a user/assistant pair, so message alternation survives the splice
            kept = (kept[:self.keep_first] +
                    [{'role': 'user', 'content': f'[Summary of earlier conversation]\n{s}'},
                     {'role': 'assistant', 'content': 'Understood.'}] + kept[self.keep_first:])
        c.hist[:] = kept
        c.evicted = getattr(c, 'evicted', 0) + len(dropped)
        c._recreate_conv()
