"""Canonical messages and wire conversions.

Docs: https://vedicreader.github.io/urai/msgs.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_msgs.ipynb.

# %% auto #0
__all__ = ['CHARS_PER_TOKEN', 'ROLE_NAMES', 'mk_content', 'is_media', 'mk_msg', 'mk_msgs', 'strip_media', 'to_media_part',
           'mk_toolspec', 'ToolCall', 'tc_name', 'mk_tool_res_msg', 'mk_tool_res_msgs', 'parse_args', 'norm_resp',
           'to_oai_msg', 'sum_usage', 'est_tokens', 'render_prompt', 'common_prefix_len']

# %% ../nbs/02_msgs.ipynb #bc883722
import json, math, os
from base64 import b64encode
from fastcore.funccall import get_schema
from fastcore.all import Path, L, first, listify, detect_mime
from aidialog.msg_parts import InputImage, InputAudio, data_url
from .core import Resp, resp_text
from .tags import split_think, parse_tool_tags

# %% ../nbs/02_msgs.ipynb #b16aa506
_audio_fmts = {'audio/wav': 'wav', 'audio/x-wav': 'wav', 'audio/wave': 'wav',
               'audio/mpeg': 'mp3', 'audio/mp3': 'mp3'}

def _audio_fmt(mime):
    "OpenAI `input_audio` format name for a MIME type."
    return _audio_fmts.get(mime, mime.split('/')[-1])

def mk_content(o):
    "`o` as an OpenAI-style content part: text, a base64 `image_url`, or an `input_audio`."
    if isinstance(o, dict): return o
    if isinstance(o, str): return {'type': 'text', 'text': o}
    if isinstance(o, os.PathLike): o = Path(o).read_bytes()
    if isinstance(o, bytes):
        mime = detect_mime(o) or 'application/octet-stream'
        if mime.startswith('image/'):
            return {'type': 'image_url',
                    'image_url': {'url': f'data:{mime};base64,{b64encode(o).decode()}'}}
        if mime.startswith('audio/'):
            return {'type': 'input_audio',
                    'input_audio': {'data': b64encode(o).decode(), 'format': _audio_fmt(mime)}}
        raise TypeError(f'chat supports text, image, and audio content, got {mime}')
    raise TypeError(f'Unsupported content type: {type(o)}')

def is_media(p):
    "Is `p` an image or audio content part?"
    return isinstance(p, dict) and p.get('type') in ('image_url', 'input_audio')

# %% ../nbs/02_msgs.ipynb #0beeff29
def mk_msg(content, role='user'):
    "An OpenAI-style message dict from a str, bytes, list, or dict."
    if content is None or isinstance(content, dict): return content
    parts = [mk_content(o) for o in content] if isinstance(content, list) else [mk_content(content)]
    if all(p.get('type') == 'text' for p in parts):
        return {'role': role, 'content': '\n'.join(p['text'] for p in parts)}
    return {'role': role, 'content': parts}

def mk_msgs(msgs):
    "Normalize a list of messages to OpenAI-style dicts."
    return [mk_msg(m) for m in listify(msgs)] if msgs else []

# %% ../nbs/02_msgs.ipynb #eaaf0126
_media_ph = {'image_url': '[image]', 'input_audio': '[audio]'}

def strip_media(m):
    "Replace media parts with a text placeholder and collapse content to a string."
    c = m.get('content')
    if not isinstance(c, list): return m
    return {**m, 'content': '\n'.join(_media_ph.get(p.get('type'), '[media]') if is_media(p)
                                      else p.get('text', '') for p in c)}

# %% ../nbs/02_msgs.ipynb #5fcf3a94
def to_media_part(p):
    "An OpenAI-style media content part as a typed aidialog `Part`, or None if `p` is not media."
    if not is_media(p): return None
    if p['type'] == 'image_url':
        image = p.get('image_url')
        url = image.get('url') if isinstance(image, dict) else image
        return InputImage(text=url, mime=(data_url(url) or (None, None))[0])
    audio = p.get('input_audio') or {}
    url = f"data:audio/{audio.get('format', 'wav')};base64,{audio.get('data', '')}"
    return InputAudio(text=url, mime=(data_url(url) or (None, None))[0])

# %% ../nbs/02_msgs.ipynb #20e32a7f
def mk_toolspec(f):
    "OpenAI-style tool spec for callable `f`. Spec dicts pass through."
    if isinstance(f, dict): return f
    sc = get_schema(f, pname='parameters')
    sc.get('parameters', {}).pop('title', None)   # get_schema adds a stray title for classes
    return {'type': 'function', 'function': sc}

# %% ../nbs/02_msgs.ipynb #e3ee206c
import uuid

class ToolCall(dict):
    "One tool call in canonical form. A `dict` subclass, so anything that indexes it keeps working."
    def __init__(self, name='', arguments=None, id=None, server=False):
        super().__init__(id=id or f'call_{uuid.uuid4().hex[:8]}', type='function',
                         function={'name': name, 'arguments': arguments if arguments is not None else {}})
        if server: self['server'] = True
    @property
    def name(self): return self['function'].get('name', '')
    @property
    def arguments(self): return self['function'].get('arguments') or {}
    @property
    def server(self):
        "True when the provider runs this tool itself, so the loop must not."
        return bool(self.get('server'))
    def __repr__(self): return f'ToolCall({self.name}, {self.arguments})'

def tc_name(tc):
    "Name of a tool call, however it was built."
    return (tc.get('function') or {}).get('name', '')

def mk_tool_res_msg(tc, result):
    "Canonical `role='tool'` message carrying `result` back for tool call `tc`."
    return {'role': 'tool', 'tool_call_id': tc.get('id'), 'name': tc_name(tc), 'content': str(result)}

def mk_tool_res_msgs(tcs, results):
    "Canonical tool-result messages for several calls at once."
    return [mk_tool_res_msg(tc, r) for tc, r in zip(tcs, results)]

# %% ../nbs/02_msgs.ipynb #14348315
def parse_args(a):
    "Parse OpenAI JSON-string tool arguments to a dict. Dicts pass through, bad JSON becomes `{}`."
    if isinstance(a, dict): return a
    try: return json.loads(a) if a else {}
    except json.JSONDecodeError: return {}

def norm_resp(r):
    "An OpenAI-style chat completion as a urai `Resp`."
    ch = r['choices'][0]
    m = ch.get('message') or {}
    text, th = split_think(m.get('content') or '')
    text, tag_tcs = parse_tool_tags(text)
    tcs = [{'id': tc.get('id'), 'type': 'function',
            'function': {'name': tc.get('function', {}).get('name', ''),
                         'arguments': parse_args(tc.get('function', {}).get('arguments'))}}
           for tc in (m.get('tool_calls') or [])] + tag_tcs
    res = {'role': 'assistant', 'content': text}
    if th: res['channels'] = {'thought': th}
    if tcs: res['tool_calls'] = tcs
    if ch.get('finish_reason') == 'length': res['truncated'] = True
    if 'usage' in r: res['usage'] = dict(r['usage'])
    return Resp(res)

# %% ../nbs/02_msgs.ipynb #59c18c9e
def to_oai_msg(m):
    "Convert a history entry to an OpenAI wire message."
    out = {k: m[k] for k in ('role', 'content', 'tool_calls', 'tool_call_id', 'name')
           if m.get(k) is not None}
    if 'tool_calls' in out:
        out['tool_calls'] = [
            {'id': tc.get('id') or f'call_{i}', 'type': 'function',
             'function': {'name': tc['function'].get('name', ''),
                          'arguments': a if isinstance((a := tc['function'].get('arguments')), str)
                                       else json.dumps(a or {})}}
            for i, tc in enumerate(out['tool_calls'])]
        out.setdefault('content', '')
    return out

# %% ../nbs/02_msgs.ipynb #32ad8ba0
def sum_usage(us):
    "Sum OpenAI usage dicts, ignoring Nones. `model` is carried through rather than summed."
    us = [u for u in us if u]
    if not us: return None
    out = {k: sum(u.get(k, 0) for u in us)
           for k in ('prompt_tokens', 'completion_tokens', 'total_tokens', 'cached_tokens')}
    for k in ('reasoning_tokens', 'cache_creation_tokens', 'cost'):   # hosted-only: absent, not 0
        if (v := sum(u.get(k, 0) for u in us)): out[k] = v
    if (m := first(us, lambda u: u.get('model'))): out['model'] = m['model']
    return out

# %% ../nbs/02_msgs.ipynb #12cff266
CHARS_PER_TOKEN = 3.25   #: measured on ornith-1.5:9b and qwen3:0.6b, which both give 3.50

def est_tokens(text):
    "Rough token count for a transport with no tokenizer of its own."
    return max(1, math.ceil(len(text) / CHARS_PER_TOKEN)) if text else 0

#: How each role is titled when a conversation is rendered as one block of text.
ROLE_NAMES = {'user': 'User', 'assistant': 'Assistant', 'tool': 'Tool result', 'system': 'System'}

def render_prompt(hist, sp=''):
    "A conversation as one block of text, for a transport that takes a prompt rather than messages."
    out = [sp] if sp else []
    for m in hist:
        if not (txt := resp_text(m)) and not m.get('tool_calls'): continue
        who = ROLE_NAMES.get(m.get('role'), m.get('role', '?'))
        if m.get('role') == 'tool': who = f"Tool result ({m.get('name', '?')})"
        calls = '\n'.join(
            '<tool_call>\n' + json.dumps({'name': tc_name(tc),
                                          'arguments': tc.get('function', {}).get('arguments') or {}})
            + '\n</tool_call>' for tc in (m.get('tool_calls') or []))
        out.append(f"## {who}\n{txt}{chr(10) + calls if calls else ''}")
    return '\n\n'.join(out)

# %% ../nbs/02_msgs.ipynb #a1342410
def common_prefix_len(a, b):
    "Length of the longest common prefix of sequences `a` and `b`."
    n = 0
    for x, y in zip(a, b):
        if x != y: break
        n += 1
    return n
