"""Portable model names and options.

Docs: https://vedicreader.github.io/urai/opts.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_opts.ipynb.

# %% auto #0
__all__ = ['RUNTIMES', 'dflt_runtime', 'DFLT_FINAL_PROMPT', 'GEN_OPTS', 'ALIASES', 'Runtime', 'register_runtime', 'split_runtime',
           'infer_runtime', 'resolve_runtime', 'ModelSpec', 'resolve', 'load_ref', 'model_caps', 'ChatOpts',
           'set_dotted', 'backend_kw', 'turn_kw']

# %% ../nbs/04_opts.ipynb #fea6fec5
import warnings
from dataclasses import dataclass, field, fields, replace
from importlib import import_module
from fastcore.all import Path, L
from .caps import Caps, hosted_caps, hosted_ctx, is_path, DFLT_CTX

# %% ../nbs/04_opts.ipynb #55e2c1fc
@dataclass(frozen=True)
class Runtime:
    "One registered backend: where its `Chat` lives and how to recognise a model of its own."
    name: str
    cls: object                # `'pkg.mod.ChatSubclass'`, or the class itself
    pats: tuple = ()           # id or path substrings that infer this runtime
    optional: bool = False     # ...so a missing import can suggest an extra instead of raising
    extra: str = ''            # the pip extra that installs it; defaults to `name`
    local: bool = True         # does it run on this machine?
    caps: object = None        # `caps(model, model_path)` prober, dotted or callable
    ctx: int = 0               # fixed window, for a runtime whose models all share one

    @property
    def install(self):
        "What to tell someone whose optional backend is missing."
        pkg = self.cls.split('.')[0] if isinstance(self.cls, str) else self.name
        return f"pip install '{pkg}[{self.extra or self.name}]'"

RUNTIMES = {}   #: name -> `Runtime`, in inference order

def register_runtime(rt, dflt=False):
    "Add `rt` to the registry. `dflt=True` also makes it what a bare `Chat()` builds."
    global dflt_runtime
    RUNTIMES[rt.name] = rt
    if dflt: dflt_runtime = rt.name
    return rt

dflt_runtime = None   #: runtime for a `Chat()` with no model named

# %% ../nbs/04_opts.ipynb #827581c0
def split_runtime(model):
    "Split `'runtime/model'` into `(runtime, model)`. The prefix must name a registered runtime."
    if isinstance(model, str) and '/' in model:
        b, m = model.split('/', 1)
        if b in RUNTIMES: return b, m
    return None, model

def infer_runtime(model):
    "Guess a runtime from the shape of a model id or path, else `None`."
    s = str(model or '').lower()
    if not s: return None
    return next((n for n, rt in RUNTIMES.items() if any(p in s for p in rt.pats)), None)

def resolve_runtime(model=None, runtime=None, model_path=None):
    "Resolve `(runtime, model)` from an explicit `runtime`, a `runtime/` prefix, or the id shape."
    pre, model = split_runtime(model)
    nm = runtime or pre or infer_runtime(model) or infer_runtime(model_path)
    if nm is None and model is None and model_path is None: nm = dflt_runtime
    if nm is None: raise ValueError(
        f"Can't tell which backend {model!r} needs. Pass runtime={'|'.join(map(repr, RUNTIMES))}, "
        f"prefix the name (e.g. 'llama/{model}'), or give a full repo id or path.")
    if nm not in RUNTIMES: raise ValueError(f'Unknown runtime {nm!r}; known: {", ".join(RUNTIMES)}.')
    return nm, model

# %% ../nbs/04_opts.ipynb #509334a3
@dataclass(frozen=True)
class ModelSpec:
    "One model, resolved: which runtime runs it, what to call it, and how big it is."
    name: str                  # what the caller typed
    runtime: str
    model_id: str              # what the backend is given
    ctx: int = DFLT_CTX        # context window in tokens
    note: str = ''             # anything worth showing about how this was resolved
    opts: dict = field(default_factory=dict, compare=False)   # runtime options; never a secret

    @property
    def rt(self): return RUNTIMES[self.runtime]
    @property
    def local(self): return self.rt.local
    def __str__(self): return f'{self.name} ({self.model_id})'

def resolve(name=None, runtime=None, model_path=None, ctx=None, **opts):
    "A `ModelSpec` for `name`, working out the runtime and the window."
    rt_name, model_id = resolve_runtime(name, runtime, model_path)
    rt, note = RUNTIMES[rt_name], ''
    if ctx is None:
        if rt.ctx: ctx = rt.ctx
        elif rt.local: ctx = DFLT_CTX
        else: ctx, note = hosted_ctx(model_id)
    return ModelSpec(name or model_id or rt_name, rt_name, model_id, ctx, note, opts)

# %% ../nbs/04_opts.ipynb #5ecdfe8b
def load_ref(o):
    "`o` itself, or the object at dotted path `'pkg.mod.name'`."
    if not isinstance(o, str): return o
    mod, _, nm = o.rpartition('.')
    return getattr(import_module(mod), nm)

def model_caps(model=None, runtime=None, model_path=None):
    "What `model` accepts and returns, resolved without loading it."
    try: nm, mid = resolve_runtime(model, runtime, model_path)
    except Exception: nm, mid = runtime, model
    mid = str(mid if mid is not None else (model or ''))
    rt = RUNTIMES.get(nm)
    if rt is None: return hosted_caps(mid)
    if rt.caps:
        try: return load_ref(rt.caps)(mid, model_path) or Caps()
        except Exception: return Caps()
    return Caps() if rt.local else hosted_caps(mid)

# %% ../nbs/04_opts.ipynb #310734f1
DFLT_FINAL_PROMPT = ("You've reached the tool-call budget for this turn. Stop calling tools and "
                     "answer with what you already have.")

#: Options that can also be set for a single turn, rather than for the whole chat.
GEN_OPTS = ('max_output_tokens', 'temp', 'top_k', 'top_p', 'seed', 'think', 'effort', 'tool_mode')

#: Names a backend used before there was a portable one. Accepted anywhere options are.
ALIASES = {'reasoning_effort': 'effort', 'temperature': 'temp', 'max_tokens': 'max_output_tokens',
           'ctx_limit': 'ctx', 'n_ctx': 'ctx', 'system': 'sp'}

@dataclass(frozen=True)
class ChatOpts:
    "Everything a chat can be configured with, under names every runtime shares."
    # the conversation
    sp: str = ''                       # system prompt
    tools: tuple = ()                  # callables, or spec dicts for provider-side tools
    messages: tuple = ()               # history to start from
    # the tool loop
    approve: object = None             # `f(tool_call) -> bool`; None runs every call
    max_steps: int = 10                # tool-call budget for one turn
    tool_max_len: int = 0              # truncate a tool result past this many characters
    parallel_tools: bool = False
    max_parallel_tools: int = 0
    final_prompt: str = DFLT_FINAL_PROMPT   # sent once the budget runs out
    cbs: tuple = ()
    default_cbs: bool = True
    # generation
    ctx: int = 0                       # context window to ask the backend for
    max_output_tokens: int = 0
    temp: float = None
    top_k: int = None
    top_p: float = None
    seed: int = None
    think: bool = None                 # False asks a reasoning model not to deliberate
    effort: str = ''                   # 'low'|'medium'|'high'|... for models that grade it
    tool_mode: str = ''                # 'native' sends schemas on the wire, 'tags' in the prompt
    # credentials
    api_key: str = ''
    api_key_env: str = ''              # ...or the variable holding it, for config that must not
    base_url: str = ''                 # carry secrets
    # anything the portable names do not cover
    extra: dict = field(default_factory=dict)

    @classmethod
    def create(cls, opts=None, **kw):
        "A `ChatOpts` from an existing one plus overrides, or from loose keywords alone."
        if opts is None: opts = cls()
        elif isinstance(opts, dict): opts = cls(**opts)
        if not kw: return opts
        kw = {ALIASES.get(k, k): v for k, v in kw.items()}
        known = {f.name for f in fields(cls)}
        extra = {**opts.extra, **{k: v for k, v in kw.items() if k not in known}}
        return replace(opts, **{k: v for k, v in kw.items() if k in known}, extra=extra)

    @property
    def key(self):
        "The API key: the explicit one, else whatever `api_key_env` names. Never stored on the object."
        import os
        return self.api_key or (os.environ.get(self.api_key_env) if self.api_key_env else None) or None

    def set(self):
        "The options actually chosen, by name. Defaults are absent, so a backend can tell them apart."
        d = {}
        for f in fields(self):
            if f.name == 'extra': continue
            v = getattr(self, f.name)
            if v != f.default and not (f.default is None and v is None): d[f.name] = v
        return d

# %% ../nbs/04_opts.ipynb #1ec3d549
def set_dotted(d, path, v):
    "Set `d['a']['b'] = v` for a path of `'a.b'`, creating the intermediate dicts."
    ks, cur = path.split('.'), d
    for k in ks[:-1]: cur = cur.setdefault(k, {})
    cur[ks[-1]] = v
    return d

def backend_kw(opts, opt_map=None, skip=(), warn=True):
    "`opts` as one backend's own keyword arguments, renamed by `opt_map` and minus `skip`."
    out, chosen = {}, opts.set()
    if (env := chosen.pop('api_key_env', None)) and 'api_key' not in chosen:
        import os
        if (v := os.environ.get(env)): chosen['api_key'] = v
    dropped = [k for k in chosen if k in skip]
    if warn and dropped:
        warnings.warn(f'ignored by this backend: {", ".join(sorted(dropped))}', stacklevel=2)
    for k, v in chosen.items():
        if k in skip: continue
        set_dotted(out, (opt_map or {}).get(k, k), v)
    return {**out, **opts.extra}

# %% ../nbs/04_opts.ipynb #1ce6a21f
def turn_kw(opts=None, **kw):
    "Return generation settings for one turn, excluding conversation and loop options."
    o = ChatOpts.create(opts, **kw)
    chosen = o.set()
    return {**{k: v for k, v in chosen.items() if k in GEN_OPTS}, **o.extra}
