"""Asking a model once, and replaying the answer forever.

Docs: https://vedicreader.github.io/urai/record.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_record.ipynb.

# %% auto #0
__all__ = ['CHAT_CACHE', 'KEY_VERSION', 'NotRecordable', 'is_transient', 'RecordCache', 'as_resp', 'canon_msg', 'CachedChat']

# %% ../nbs/09_record.ipynb #463c0c69
import json, os, re
from hashlib import sha256
from fastcore.all import L, Path, store_attr, ifnone, listify, str2bool
from .core import Resp, UsageStats, resp_text
from .msgs import is_media, tc_name
from .chat import Chat

# %% ../nbs/09_record.ipynb #43700c29
class NotRecordable(TypeError):
    "A reply that cannot be stored as one. Never cached, so the next ask tries again."


# %% ../nbs/09_record.ipynb #3b458012
CHAT_CACHE = 'chatcache'   #: default diskcache directory
KEY_VERSION = 3            #: part of every key; bump to invalidate every recording everywhere

_transient_re = re.compile(
    r'rate.?limit|timed? ?out|timeout|temporarily|try again|50[234]\b|429', re.I)

def is_transient(e):
    """Is `e` a failure of the moment rather than of the ask? Those are not worth remembering.

    A reply that cannot be stored counts: caching it would replay the refusal instead of the
    answer, and the next ask would never get a chance to record one.
    """
    if isinstance(e, NotRecordable): return True
    return isinstance(e, (ConnectionError, TimeoutError, OSError)) or bool(_transient_re.search(str(e)))

# %% ../nbs/09_record.ipynb #1734deca
class RecordCache:
    "Record what a call returned the first time and replay it after. The primitive under `CachedChat`."
    def __init__(self,
                 path=None,     # the diskcache directory; None -> `CHAT_CACHE`
                 record=None,   # let a miss run for real; None -> read `env`
                 env='URAI_RECORD_CHAT',
                 version=None): # part of every key; None -> `KEY_VERSION`
        try: from diskcache import Cache
        except ImportError as e: raise ImportError(
            "RecordCache needs diskcache, which urai does not install by default: "
            "pip install 'urai[record]'") from e
        self.cache, self.env = Cache(str(path or CHAT_CACHE)), env
        self.version = ifnone(version, KEY_VERSION)
        self.record = str2bool(os.getenv(env) or '') if record is None else record

    def key(self, *parts):
        "Stable hash of `parts`, with the cache version in it."
        return sha256(json.dumps([self.version, *parts], sort_keys=True,
                                 default=str).encode()).hexdigest()

    def __call__(self, key, f, what=''):
        "Replay `key`, else run `f()` and record what it did, including how it failed."
        if key in self.cache:
            got, val = self.cache[key]
            if got == 'exc': raise RuntimeError(val)
            return val
        if not self.record: raise KeyError(
            f'no recording for {what or key[:16]} - set {self.env}=1 and re-run to record it')
        try: val = f()
        except Exception as e:
            if not is_transient(e): self.cache[key] = ('exc', f'{type(e).__name__}: {e}')
            raise
        self.cache[key] = ('ok', val)
        return val

    def forget(self, key):
        "Drop one recording, for when what it captured was never the truth. Was there one?"
        return self.cache.pop(key, None) is not None

# %% ../nbs/09_record.ipynb #acdefa8b
def as_resp(r):
    """One reply as something recordable.

    Most backends answer with a mapping. A local engine may answer with plain text, and `dict()`
    on a string raises a `ValueError` about sequence lengths rather than saying what is wrong.

    Anything else is refused rather than coerced. A streamed turn arrives here as a generator, and
    recording its `repr` would store a memory address as the answer and replay it for ever.
    """
    if isinstance(r, str): return {'role': 'assistant', 'content': r}
    try: return dict(r)
    except (TypeError, ValueError) as e:
        raise NotRecordable(f'cannot record a {type(r).__name__} as a reply') from e


def canon_msg(m):
    "What a reply depends on in one history entry: who spoke, what was said, what was attached, what was called."
    media = [sha256(str(p).encode()).hexdigest()[:16] for p in listify(m.get('content')) if is_media(p)]
    tcs = [(tc_name(tc), (tc.get('function') or {}).get('arguments')) for tc in (m.get('tool_calls') or [])]
    return [m.get('role', ''), resp_text(m), media, tcs]

# %% ../nbs/09_record.ipynb #1284922e
class CachedChat:
    "A `Chat` whose replies are recorded to disk and replayed on a second ask. A replay builds no engine."
    def __init__(self,
                 model=None,   # anything `Chat` takes; part of the key
                 path=None,    # the diskcache directory; None -> `CHAT_CACHE`
                 record=None,  # let a miss reach a real model; None -> `$URAI_RECORD_CHAT`
                 sp='',        # system prompt, part of the key
                 tools=None,   # tool *names* are part of the key; the real chat gets the tools
                 **kw):        # forwarded to `Chat` on a miss
        store_attr('model,sp,kw')
        self.tools, self.rec, self._chat, self.hist = L(tools), RecordCache(path, record), None, []
        self.use = UsageStats()   # folded from every reply, replayed or live, like `Chat.use`
        self._ctx = 0             # occupancy the answering chat reported. See `token_count`

    @property
    def cache(self): return self.rec.cache

    @property
    def token_count(self):
        "Tokens the conversation occupies, as the chat that answered reported them."
        return self._ctx

    def cancel(self):
        "Stop the live turn, if one was ever built. Nothing to stop while replaying."
        return self._chat.cancel() if self._chat is not None else False

    @property
    def cancelled(self): return self._chat is not None and self._chat.cancelled

    @property
    def chat(self):
        "The real `Chat`, built only when something actually has to be asked."
        if self._chat is None:
            self._chat = Chat(self.model, sp=self.sp, tools=list(self.tools),
                              messages=self.hist, **self.kw)
        return self._chat

    def _fold(self, u, ctx=None):
        """Add one reply's usage block to `use`, the way `UsageCallback` does for a live chat.

        A recording holds what the call actually cost, so a replay reports it. Without this a
        replayed turn looked free, and anything sized by what a call cost could not be tested.
        """
        u = u or {}
        self.use += UsageStats(
            u.get('prompt_tokens', 0), u.get('completion_tokens', 0), u.get('total_tokens', 0), 1,
            cached_tokens=u.get('cached_tokens', 0), model=u.get('model') or self.model,
            reasoning_tokens=u.get('reasoning_tokens', 0),
            cache_creation_tokens=u.get('cache_creation_tokens', 0), cost=u.get('cost', 0.0))
        # a turn's usage block sums its model steps, so it is what the turn cost and not what the
        # window holds. Occupancy is the answering chat's own count, recorded beside the reply
        if ctx: self._ctx = ctx
        elif t := u.get('total_tokens'): self._ctx = t   # recorded before `ctx` was stored
        return self.use

    def _key(self, kind, *args, hist=True):
        "What a reply is recorded under. `hist=False` is for asks that are stateless by definition."
        return self.rec.key(self.model, kind, self.sp, self.kw,
                            [getattr(t, '__name__', str(t)) for t in self.tools],
                            [canon_msg(m) for m in self.hist] if hist else [], *args)

    def _ask(self, kind, args, f, hist=True):
        "Replay this ask if it is recorded, else run `f()` and record it."
        n = len(self.hist) if hist else 0
        what = f'{kind} for {self.model} after {n} messages: {str(args[0])[:80]}'
        return self.rec(self._key(kind, *args, hist=hist), f, what)

    def __call__(self, prompt, **kw):
        "One turn, replayed if it has been asked before. `hist` ends up as the real turn left it."
        key = self._key('call', prompt, kw)
        hit = key in self.rec.cache
        what = f'call for {self.model} after {len(self.hist)} messages: {str(prompt)[:80]}'
        def _live():
            n = len(self.chat.hist)
            r = self.chat(prompt, **kw)
            return dict(resp=as_resp(r), hist=[dict(m) for m in self.chat.hist[n:]],
                        ctx=getattr(self.chat, 'token_count', 0))
        rec = self.rec(key, _live, what)
        self._fold(rec['resp'].get('usage'), rec.get('ctx'))
        # a stopped turn is a truncated one, and a recording would replay the truncation forever
        if not hit and self.cancelled: self.rec.forget(key)
        self.hist += [dict(m) for m in rec['hist']]
        # a replayed turn never reached the live chat, so hand it the history it missed
        if hit and self._chat is not None:
            self._chat.hist = list(self.hist)
            self._chat._recreate_conv()
        return Resp(rec['resp'])

    def oneshot(self, prompt, sp='', think=None, max_tokens=None):
        return self._ask('oneshot', [prompt, sp, think, max_tokens], hist=False,
                         f=lambda: self.chat.oneshot(prompt, sp, think=think, max_tokens=max_tokens))

    def classify(self, text, labels, **kw):
        return self._ask('classify', [text, list(labels), kw], hist=False,
                         f=lambda: self.chat.classify(text, labels, **kw))

    def reconfigure(self, sp=None, tools=None):
        "Change `sp` or `tools` for the asks that follow. Both are in the key, so a replay stays honest."
        if sp is not None: self.sp = sp
        if tools is not None: self.tools = L(tools)
        if self._chat is not None: self._chat.reconfigure(sp=sp, tools=tools)
        return self

    def close(self):
        if self._chat is not None: self._chat.close(); self._chat = None
