"""Asking a model once, and replaying the answer forever.

Docs: https://vedicreader.github.io/urai/record.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_record.ipynb.

# %% auto #0
__all__ = ['CHAT_CACHE', 'KEY_VERSION', 'RECORD_ENV', 'is_transient', 'RecordCache', 'replaying', 'canon_msg', 'CachedChat',
           'RecordedChat']

# %% ../nbs/09_record.ipynb #463c0c69
import json, os, re, shutil, tempfile
from contextlib import contextmanager
from hashlib import sha256
from fastcore.all import L, Path, store_attr, ifnone, listify, str2bool
from .core import Resp, resp_text
from .msgs import is_media, tc_name, est_tokens, render_prompt
from .caps import DFLT_CTX
from .opts import ChatOpts
from .chat import Chat
from .loop import ToolLoopMixin, UsageCallback, ToolReminderCallback, SlidingWindowCallback

# %% ../nbs/09_record.ipynb #3b458012
CHAT_CACHE = 'chatcache'   #: default diskcache directory
KEY_VERSION = 3            #: part of every key; bump to invalidate every recording everywhere
RECORD_ENV = 'URAI_RECORD_CHAT'   #: asked when no caller said whether a miss may reach a model

_transient_re = re.compile(
    r'rate.?limit|timed? ?out|timeout|temporarily|try again|50[234]\b|429', re.I)

def is_transient(e):
    "Is `e` a failure of the moment rather than of the ask? Those are not worth remembering."
    return isinstance(e, (ConnectionError, TimeoutError, OSError)) or bool(_transient_re.search(str(e)))

# %% ../nbs/09_record.ipynb #1734deca
class RecordCache:
    "Record what a call returned the first time and replay it after. The primitive under `CachedChat`."
    def __init__(self,
                 path=None,     # the diskcache directory; None -> `CHAT_CACHE`
                 record=None,   # let a miss run for real; None -> read `env`
                 env=RECORD_ENV,
                 version=None): # part of every key; None -> `KEY_VERSION`
        try: from diskcache import Cache
        except ImportError as e: raise ImportError(
            "RecordCache needs diskcache, which urai does not install by default: "
            "pip install 'urai[record]'") from e
        self.cache, self.env = Cache(str(path or CHAT_CACHE)), env
        self.version = ifnone(version, KEY_VERSION)
        self.record = str2bool(os.getenv(env) or '') if record is None else record

    def key(self, *parts):
        "Stable hash of `parts`, with the cache version in it."
        return sha256(json.dumps([self.version, *parts], sort_keys=True,
                                 default=str).encode()).hexdigest()

    def __call__(self, key, f, what=''):
        "Replay `key`, else run `f()` and record what it did, including how it failed."
        if key in self.cache:
            got, val = self.cache[key]
            if got == 'exc': raise RuntimeError(val)
            return val
        if not self.record: raise KeyError(
            f'no recording for {what or key[:16]} - set {self.env}=1 and re-run to record it')
        try: val = f()
        except Exception as e:
            if not is_transient(e): self.cache[key] = ('exc', f'{type(e).__name__}: {e}')
            raise
        self.cache[key] = ('ok', val)
        return val

    def forget(self, key):
        "Drop one recording, for when what it captured was never the truth. Was there one?"
        return self.cache.pop(key, None) is not None

# %% ../nbs/09_record.ipynb #caece4b2
@contextmanager
def replaying(path=None,        # the diskcache directory; None -> `CHAT_CACHE`
              record=None,      # let a miss reach a real model; None -> read `env`
              env=RECORD_ENV):  # which variable that is
    """`(directory, record)` for a `RecordCache`: the real one to record into, a copy to replay from.

    Yield both, never one: which directory this is and whether the cache in it may write are the
    same question, and answering it twice is how a replay ends up writing to the artefact it was
    supposed to leave alone -- or a recording ends up in a copy that is about to be deleted."""
    rec = str2bool(os.getenv(env) or '') if record is None else bool(record)
    p = Path(path or CHAT_CACHE)
    if rec or not p.exists():
        p.mkdir(parents=True, exist_ok=True)
        yield p, rec
        return
    d = Path(tempfile.mkdtemp())/'chats'
    shutil.copytree(p, d)
    try: yield d, rec
    finally: shutil.rmtree(d, ignore_errors=True)

# %% ../nbs/09_record.ipynb #acdefa8b
def canon_msg(m):
    "What a reply depends on in one history entry: who spoke, what was said, what was attached, what was called."
    media = [sha256(str(p).encode()).hexdigest()[:16] for p in listify(m.get('content')) if is_media(p)]
    tcs = [(tc_name(tc), (tc.get('function') or {}).get('arguments')) for tc in (m.get('tool_calls') or [])]
    return [m.get('role', ''), resp_text(m), media, tcs]

# %% ../nbs/09_record.ipynb #1284922e
class CachedChat:
    "A `Chat` whose replies are recorded to disk and replayed on a second ask. A replay builds no engine."
    def __init__(self,
                 model=None,   # anything `Chat` takes; part of the key
                 path=None,    # the diskcache directory; None -> `CHAT_CACHE`
                 record=None,  # let a miss reach a real model; None -> `$URAI_RECORD_CHAT`
                 sp='',        # system prompt, part of the key
                 tools=None,   # tool *names* are part of the key; the real chat gets the tools
                 **kw):        # forwarded to `Chat` on a miss
        store_attr('model,sp,kw')
        self.tools, self.rec, self._chat, self.hist = L(tools), RecordCache(path, record), None, []

    @property
    def cache(self): return self.rec.cache

    def cancel(self):
        "Stop the live turn, if one was ever built. Nothing to stop while replaying."
        return self._chat.cancel() if self._chat is not None else False

    @property
    def cancelled(self): return self._chat is not None and self._chat.cancelled

    @property
    def chat(self):
        "The real `Chat`, built only when something actually has to be asked."
        if self._chat is None:
            self._chat = Chat(self.model, sp=self.sp, tools=list(self.tools),
                              messages=self.hist, **self.kw)
        return self._chat

    def _key(self, kind, *args, hist=True):
        "What a reply is recorded under. `hist=False` is for asks that are stateless by definition."
        return self.rec.key(self.model, kind, self.sp, self.kw,
                            [getattr(t, '__name__', str(t)) for t in self.tools],
                            [canon_msg(m) for m in self.hist] if hist else [], *args)

    def _ask(self, kind, args, f, hist=True):
        "Replay this ask if it is recorded, else run `f()` and record it."
        n = len(self.hist) if hist else 0
        what = f'{kind} for {self.model} after {n} messages: {str(args[0])[:80]}'
        return self.rec(self._key(kind, *args, hist=hist), f, what)

    def __call__(self, prompt, **kw):
        "One turn, replayed if it has been asked before. `hist` ends up as the real turn left it."
        key = self._key('call', prompt, kw)
        hit = key in self.rec.cache
        what = f'call for {self.model} after {len(self.hist)} messages: {str(prompt)[:80]}'
        def _live():
            n = len(self.chat.hist)
            r = self.chat(prompt, **kw)
            return {'resp': dict(r), 'hist': [dict(m) for m in self.chat.hist[n:]]}
        rec = self.rec(key, _live, what)
        # a stopped turn is a truncated one, and a recording would replay the truncation forever
        if not hit and self.cancelled: self.rec.forget(key)
        self.hist += [dict(m) for m in rec['hist']]
        # a replayed turn never reached the live chat, so hand it the history it missed
        if hit and self._chat is not None:
            self._chat.hist = list(self.hist)
            self._chat._recreate_conv()
        return Resp(rec['resp'])

    def oneshot(self, prompt, sp='', think=None, max_tokens=None):
        return self._ask('oneshot', [prompt, sp, think, max_tokens], hist=False,
                         f=lambda: self.chat.oneshot(prompt, sp, think=think, max_tokens=max_tokens))

    def classify(self, text, labels, **kw):
        return self._ask('classify', [text, list(labels), kw], hist=False,
                         f=lambda: self.chat.classify(text, labels, **kw))

    def reconfigure(self, sp=None, tools=None):
        "Change `sp` or `tools` for the asks that follow. Both are in the key, so a replay stays honest."
        if sp is not None: self.sp = sp
        if tools is not None: self.tools = L(tools)
        if self._chat is not None: self._chat.reconfigure(sp=sp, tools=tools)
        return self

    def close(self):
        if self._chat is not None: self._chat.close(); self._chat = None

# %% ../nbs/09_record.ipynb #18046877
class RecordedChat(ToolLoopMixin, Chat):
    "A real `Chat` whose wire calls are recorded once and replayed after. See `CachedChat` for the wrapper it replaces."

    _runtime = 'recorded'
    _dflt_cbs = [UsageCallback, ToolReminderCallback, SlidingWindowCallback]

    def __new__(cls, *args, **kw): return object.__new__(cls)   # never re-routed by runtime

    def __init__(self,
                 model=None,        # anything `Chat` takes; part of every key
                 *,
                 path=None,         # the diskcache directory; None -> `CHAT_CACHE`
                 record=None,       # let a miss reach a real model; None -> read `env`
                 env=None,          # which variable that is; None -> `RECORD_ENV`
                 runtime=None,      # forced runtime for the live chat
                 model_path=None,
                 opts=None,
                 ctx_limit=None,
                 **kw):             # the live chat's own constructor arguments
        o = ChatOpts.create(opts, **({'ctx_limit': ctx_limit} if ctx_limit else {}), **kw)
        self.model, self.model_path, self._rt = model, model_path, runtime
        # the loose keywords, kept as they arrived: a backend's own constructor arguments
        # (`workspace`, `engine`, `quant`) are named parameters there, not portable options,
        # and `ChatOpts` would carry them into `extra` and hand them to the wire instead
        self._kw = {**({'ctx_limit': ctx_limit} if ctx_limit else {}), **kw}
        self.rec = RecordCache(path, record, env=env or RECORD_ENV)
        self._chat, self._ctx_tokens = None, 0
        self._set_tools(o.tools)               # `toolspecs` and `ns`: `_setup` sets `tools` alone
        self.ctx_limit = o.ctx or DFLT_CTX
        self._setup(model, o)

    @property
    def chat(self):
        "The live `Chat`, built on the first miss. A full replay never touches this."
        if self._chat is None:
            self._chat = Chat(self.model, runtime=self._rt, model_path=self.model_path, **self._kw)
        return self._chat

    def _live(self):
        "The live chat, holding exactly the conversation this one holds."
        c = self.chat
        c.hist = [dict(m) for m in self.hist]
        c._recreate_conv()
        return c

    def _key(self, kind, *args, hist=True):
        "What one call is recorded under: the model, the briefing, the tools, and the conversation."
        return self.rec.key(self.model, self._rt, kind, self.sp,
                            [getattr(t, '__name__', str(t)) for t in self.tools],
                            [canon_msg(m) for m in self.hist] if hist else [], *args)

    def _what(self, kind):
        last = resp_text(self.hist[-1]) if self.hist else ''
        return f'{kind} for {self.model} after {len(self.hist)} messages: {last[:80]}'

    def _model_step(self, max_output_tokens=None, **kw):
        res = self.rec(self._key('step', kw), lambda: dict(self._live()._model_step(**kw)),
                       self._what('step'))
        return Resp(res)

    def _stream_step(self, max_output_tokens=None, **kw):
        def live():
            c = self._live()
            chunks = [o for o in c._stream_step(**kw)]
            return {'chunks': chunks, 'res': dict(c._step_res)}
        rec = self.rec(self._key('stream', kw), live, self._what('stream'))
        yield from rec['chunks']
        self._step_res = Resp(rec['res'])

    def _oneshot(self, prompt, sp='', think=None, max_tokens=None):
        return self.rec(self._key('oneshot', prompt, sp, think, max_tokens, hist=False),
                        lambda: self.chat.oneshot(prompt, sp, think=think, max_tokens=max_tokens),
                        f'oneshot for {self.model}: {str(prompt)[:80]}')

    @property
    def token_count(self):
        "The live chat's count where there is one, else the estimate every backend falls back to."
        if self._chat is not None: return self._chat.token_count
        return est_tokens(render_prompt(self.hist)) + est_tokens(self.sp)

    def count_tokens(self, text):
        f = getattr(self._chat, 'count_tokens', None)
        return f(text) if f else est_tokens(str(text or ''))

    def close(self):
        if self._chat is not None: self._chat.close(); self._chat = None
