"""Running Python fences produced by a model.

Docs: https://vedicreader.github.io/urai/sandbox.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_sandbox.ipynb.

# %% auto #0
__all__ = ['extract_code', 'mk_result_fence', 'run_coro', 'task_complete', 'output_matches', 'PyFenceCallback', 'sync_iter',
           'killed_on_exit']

# %% ../nbs/08_sandbox.ipynb #6b1d1e27
import asyncio, io, re, subprocess, warnings
from contextlib import contextmanager, redirect_stdout
from concurrent.futures import ThreadPoolExecutor
from fastcore.all import L, store_attr, patch
from safepyrun import RunPython
from .core import ChatCallback, resp_text
from .chat import Chat
from .eval import matches_

# %% ../nbs/08_sandbox.ipynb #17e03f31
_pyfence_re = re.compile(r'^```(?:python|py)[ \t]*\n(.*?)\n```', re.DOTALL | re.MULTILINE)

def extract_code(text):
    "Code of the last ```python fence in `text`, else None."
    return ms[-1] if (ms := _pyfence_re.findall(text or '')) else None

def mk_result_fence(out):
    "Feed a code result back, asking for prose or for more code."
    return (f'```result\n{out}\n```\n\nIf this answers the request, reply with the final answer in '
            'prose; only write another ```python block if you need to run more code.')

# %% ../nbs/08_sandbox.ipynb #aee62814
@patch
def run_py(self:Chat, code, ban_defs=False, g=None):
    "Run `code` in this chat's sandboxed, persistent namespace. Returns stdout plus the last expression."
    if not hasattr(self, '_pyrun'): self._pyrun = RunPython(g=g, ban_defs=ban_defs)
    buf = io.StringIO()
    try:
        with redirect_stdout(buf): res = run_coro(self._pyrun(code))
        out = buf.getvalue()
        if res is not None: out = (out + '\n' if out else '') + repr(res)
        return out or '(ok)'
    except Exception as e: return f'{type(e).__name__}: {e}'

def run_coro(coro):
    "Run an awaitable to completion from sync code, even inside a running event loop."
    try: asyncio.get_running_loop()
    except RuntimeError: return asyncio.run(coro)
    with ThreadPoolExecutor(1) as ex: return ex.submit(asyncio.run, coro).result()

# %% ../nbs/08_sandbox.ipynb #af46384a
def task_complete(chat):
    "`done` policy: ask the model, in isolation, whether the latest result completes the request."
    convo = '\n'.join(f"{m.get('role','?')}: {resp_text(m)}" for m in chat.hist[-6:])
    return chat.classify(convo, ['complete', 'needs_more_work']) == 'complete'

def output_matches(expected):
    "`done` policy: stop once the last code output contains `str(expected)`."
    return lambda chat: matches_(getattr(chat, 'turn_code_out', ''), expected)

class PyFenceCallback(ChatCallback):
    "Run ```python fences, feed results back, and loop until `done(chat)` or no fence is left."
    order = 50
    def __init__(self,
                 max_rounds=5,       # safety cap on rounds of code in one turn
                 done=None,          # `done(chat) -> bool`; None means "stop when there is no fence"
                 pyrun:callable=None # runner to use instead of `chat.run_py`
                ):
        store_attr(); self._depth = 0; self._warned = False

    def _active(self):
        "Only the last-registered callback drives a turn, so a per-call `done` beats a persistent one."
        cbs = getattr(self.chat, 'cbs', L())
        later = self in cbs and any(isinstance(cb, PyFenceCallback) for cb in cbs[cbs.index(self)+1:])
        if later and not self._warned:
            warnings.warn('This chat already has a PyFenceCallback; the last-registered one drives the turn.')
            self._warned = True
        return not later

    def _run_code(self):
        "Run the last fence. `(output, done)`, or `(None, False)` at the cap or with no fence."
        if self._depth >= self.max_rounds: return None, False
        code = extract_code(resp_text(self.chat.turn_res))
        if not code: return None, False
        tc = {'function': {'name': 'python', 'arguments': {'code': code}}}
        fn = self.pyrun or self.chat.run_py
        out = 'Denied by human' if (self.chat.approve and not self.chat.approve(tc)) else fn(code)
        self.chat.turn_code_out = out
        return out, bool(self.done and self.done(self.chat))

    def after_response(self):
        "Feed the result back: synchronously, or as a chunk generator during a streamed turn."
        if not self._active(): return
        if getattr(self.chat, '_streaming', False): return self._after_stream()
        out, done = self._run_code()
        if out is None: return
        self._depth += 1
        try:
            # when done, record the clean output rather than spending another model call on it
            if done: self.chat.hist.append(self.chat.fmt2hist([out])[0])
            else: self.chat._send(mk_result_fence(out))
        finally: self._depth -= 1

    def _after_stream(self):
        "Emit the result into the stream, then stream the follow-up reply unless we are done."
        out, done = self._run_code()
        if out is None: return
        self._depth += 1
        try:
            if done:
                self.chat.hist.append(self.chat.fmt2hist([out])[0])
                yield f'\n\n```result\n{out}\n```\n'
                return
            rf = mk_result_fence(out)
            yield '\n\n' + rf + '\n\n'
            yield from self.chat._stream(rf)
        finally: self._depth -= 1

# %% ../nbs/08_sandbox.ipynb #354a026f
def sync_iter(agen_fn, stop=None):
    "Drive the async generator from `agen_fn()` in sync code. Set `stop` to end the source stream."
    from queue import Queue
    from threading import Thread
    q, done = Queue(), object()
    async def _pump():
        agen = agen_fn()
        try:
            async for o in agen:
                q.put(o)
                if stop is not None and stop.is_set(): break
        except BaseException as e: q.put(e)
        finally:
            try: await agen.aclose()
            except BaseException: pass
            q.put(done)
    t = Thread(target=lambda: asyncio.run(_pump()), daemon=True)
    t.start()
    try:
        while (o := q.get()) is not done:
            if isinstance(o, BaseException): raise o
            yield o
    finally: t.join(timeout=5)

@contextmanager
def killed_on_exit(proc, timeout=2):
    """Wait for `proc` on success. Terminate it if the block exits early or raises."""
    try: yield proc
    except BaseException:
        if proc.poll() is None:
            proc.terminate()
            try: proc.wait(timeout)
            except subprocess.TimeoutExpired: proc.kill(); proc.wait()
        for p in (proc.stdin, proc.stdout, proc.stderr):
            if p is not None:
                try: p.close()
                except Exception: pass
        raise
    else: proc.wait()
