"""Reading thinking and tool calls out of plain text.

Docs: https://vedicreader.github.io/urai/tags.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_tags.ipynb.

# %% auto #0
__all__ = ['TAG_ARG_KEYS', 'TAG_TOOLS_SP', 'split_think', 'loose_json', 'salvage_name', 'mk_tc', 'tag_args', 'mk_tag_tc',
           'parse_fn_tags', 'lone_tag_tc', 'parse_tool_tags_ex', 'parse_tool_tags', 'tag_call_shape', 'tag_tools_sp',
           'RAW_DUMP', 'dump_raw', 'StreamSplit', 'acc_tc']

# %% ../nbs/01_tags.ipynb #f1d513cc
import json, os, re, uuid
from fastcore.all import L

# %% ../nbs/01_tags.ipynb #e99537e7
_think_re = re.compile(r'<think>(.*?)</think>', re.DOTALL)

def split_think(text):
    "Split `<think>...</think>` out of `text`, returning `(clean_text, thought)`."
    text = text or ''
    ths = [m.strip() for m in _think_re.findall(text)]
    text = _think_re.sub('', text)
    if '<think>' in text:            # unterminated, e.g. cut off at the token cap
        text, _, rest = text.partition('<think>')
        ths.append(rest.strip())
    return text.strip('\n'), '\n'.join(th for th in ths if th)

# %% ../nbs/01_tags.ipynb #8f4aec56
_ESC = {'"':'"', '\\':'\\', '/':'/', 'b':'\b', 'f':'\f', 'n':'\n', 'r':'\r', 't':'\t'}
_WS = ' \t\r\n'

def _ws(s, i):
    while i < len(s) and s[i] in _WS: i += 1
    return i

def _loose_str(s, i, ends):
    "Read a string at `s[i]`, closing only on a quote whose next non-space byte is in `ends`."
    out, i, n = [], i+1, len(s)
    while i < n:
        c = s[i]
        if c == '\\' and i+1 < n:
            e = s[i+1]
            if e in _ESC: out.append(_ESC[e]); i += 2; continue
            if e == 'u' and i+5 < n:
                try: out.append(chr(int(s[i+2:i+6], 16))); i += 6; continue
                except ValueError: pass
            out.append(e); i += 2; continue
        if c == '"':
            j = _ws(s, i+1)
            if j >= n or s[j] in ends: return ''.join(out), i+1, True
            out.append(c); i += 1; continue      # an inner quote the model never escaped
        out.append(c); i += 1                    # raw control bytes ride through as themselves
    return ''.join(out), i, False                # ran off the end: truncated

_LITS = {'true': True, 'false': False, 'null': None, 'True': True, 'False': False, 'None': None}

def _bare(tok):
    "A bare (unquoted) token as the value it spells, or as itself when it spells nothing else."
    if tok in _LITS: return _LITS[tok]
    if len(tok) > 1 and tok[0] == tok[-1] == "'": return tok[1:-1]     # a single-quoted string
    try: return int(tok)
    except ValueError: pass
    try: return float(tok)
    except ValueError: return tok

# %% ../nbs/01_tags.ipynb #33806a1b
def _loose_val(s, i, ends):
    "Read one value at `s[i]`, returning `(value, next_i, complete)`."
    i = _ws(s, i)
    if i >= len(s): return None, i, False
    c = s[i]
    if c == '"': return _loose_str(s, i, ends)
    if c == '{': return _loose_obj(s, i)
    if c == '[': return _loose_arr(s, i)
    j, depth = i, 0
    while j < len(s) and not (depth == 0 and s[j] in ends):    # a bare value runs to its own closer
        if s[j] in '{[': depth += 1
        elif s[j] in '}]': depth -= 1
        j += 1
    return _bare(s[i:j].strip()), j, j < len(s)

def _loose_obj(s, i):
    "Read an object at `s[i]`, returning `(dict, next_i, complete)`."
    out, i, n = {}, i+1, len(s)
    while True:
        i = _ws(s, i)
        if i >= n: return out, i, False
        if s[i] == '}': return out, i+1, True
        if s[i] == ',': i += 1; continue
        if s[i] == '"': k, i, ok = _loose_str(s, i, ':')
        else:
            j = i
            while j < n and s[j] not in ':,}': j += 1
            k, i, ok = s[i:j].strip().strip('\'"'), j, j < n
        if not ok: return out, i, False
        i = _ws(s, i)
        if i < n and s[i] == ':': i += 1
        v, i, ok = _loose_val(s, i, ',}')
        if not ok: return out, i, False        # the value was cut: it never lands in `out`
        out[k] = v

def _loose_arr(s, i):
    "Read an array at `s[i]`, returning `(list, next_i, complete)`."
    out, i, n = [], i+1, len(s)
    while True:
        i = _ws(s, i)
        if i >= n: return out, i, False
        if s[i] == ']': return out, i+1, True
        if s[i] == ',': i += 1; continue
        v, i, ok = _loose_val(s, i, ',]')
        if not ok: return out, i, False
        out.append(v)

def loose_json(s):
    "Parse `s` as a JSON object, tolerating what models get wrong. `(obj, complete)`, or `(None, False)`."
    s = (s or '').strip()
    if not s.startswith('{'): return None, False
    try: return json.loads(s), True                # strict wins, so conforming input is untouched
    except json.JSONDecodeError: pass
    obj, _, ok = _loose_obj(s, 0)
    return (obj, ok) if isinstance(obj, dict) else (None, False)

# %% ../nbs/01_tags.ipynb #6acee589
_name_re = re.compile(r'"name"\s*:\s*"([^"\\]{1,128})"')

def salvage_name(s):
    "The tool name from a call cut inside its own object, or None. Depth 1 only: a nested `name` is data."
    depth, i, n = 0, 0, len(s or '')
    while i < n:
        c = s[i]
        if c == '"':
            if depth == 1 and (m := _name_re.match(s, i)): return m.group(1)
            _, i, _ = _loose_str(s, i, ',}]:')
            continue
        if c in '{[': depth += 1
        elif c in '}]': depth -= 1
        i += 1
    return None

# %% ../nbs/01_tags.ipynb #7112f541
def mk_tc(name, args=None):
    "A tool_call dict in the canonical OpenAI shape."
    return {'id': f'call_{uuid.uuid4().hex[:8]}', 'type': 'function',
            'function': {'name': name, 'arguments': args or {}}}

# %% ../nbs/01_tags.ipynb #e263321a
TAG_ARG_KEYS = ('arguments', 'input', 'parameters')

def tag_args(d):
    "The argument dict of a tagged call, decoding the JSON string some models send instead."
    for k in TAG_ARG_KEYS:
        if (v := d.get(k)) is None: continue
        if isinstance(v, str):
            v = loose_json(v)[0]
            if v is None: continue
        if isinstance(v, dict): return v
    return {}

def mk_tag_tc(s):
    "A tool_call dict from the body of a `<tool_call>` block, or None. Strict, then repaired, then salvaged."
    d, ok = loose_json(s)
    if d is not None and d.get('name'):
        return mk_tc(d['name'], tag_args(d) if ok else {})   # a cut object never ships partial values
    if (name := salvage_name(s or '')): return mk_tc(name, {})
    return None

# %% ../nbs/01_tags.ipynb #d6731f91
_fn_re   = re.compile(r'<function\s*=\s*([A-Za-z_][\w.\-]*)\s*>', re.I)
_fnend_re = re.compile(r'</function\s*>', re.I)
#: only a CLOSED parameter is a complete one, so a cut call ships the name and whatever finished
_par_re  = re.compile(r'<parameter\s*=\s*([A-Za-z_][\w.\-]*)\s*>(.*?)</parameter\s*>', re.I | re.S)
_num_re  = re.compile(r'-?\d+(?:\.\d+)?$')

def _unframe(v):
    "Drop the one framing newline the template puts on each side of a value, and nothing else."
    if v.startswith('\n'): v = v[1:]
    if v.endswith('\n'): v = v[:-1]
    return v

def _spelled(v):
    "A parameter value as the JSON it spells, else as the raw string it is."
    t = v.strip()
    if t[:1] in '{[' or t in ('true', 'false', 'null') or _num_re.match(t):
        try: return json.loads(t)
        except json.JSONDecodeError: pass
    return v

def parse_fn_tags(text):
    "Calls in the `<function=name><parameter=key>` XML dialect, which Qwen 3.5+ templates mandate."
    out = []
    for m in _fn_re.finditer(text or ''):
        body = text[m.end():]
        if (e := _fnend_re.search(body)): body = body[:e.start()]
        args = {k: _spelled(_unframe(v)) for k, v in _par_re.findall(body)}
        if not args and (d := loose_json(body)[0]): args = d
        out.append(mk_tc(m.group(1), args))
    return out

# %% ../nbs/01_tags.ipynb #9482f0de
_res_tags = ('tool_result', 'tool_results', 'function_result', 'function_results',
             'tool_function_result', 'tool_function_results',
             'tool_function_call', 'tool_function_calls',
             'function_call', 'function_calls', 'tool_use')
_toolres_re = re.compile('|'.join(rf'</?{t}>>?' for t in _res_tags) + r'|</?tool_call>', re.I)
_toolcall_re = re.compile(r'<tool_call>\s*(.*?)\s*</tool_call>', re.DOTALL)
_fnblk_re = re.compile(r'<function\s*=.*?(?:</function\s*>|$)', re.I | re.S)
_fence_re = re.compile(r'^```(?:json)?\s*|\s*```$')

def lone_tag_tc(text, names=None):
    "A whole reply that is one bare call object: what the tags asked for, without the tags."
    s = _fence_re.sub('', (text or '').strip()).strip()
    if not (s.startswith('{') and s.endswith('}')): return None
    d, ok = loose_json(s)
    if not ok or not isinstance(d, dict) or not d.get('name'): return None
    if not any(k in d for k in TAG_ARG_KEYS): return None
    # inferred, not tagged: it must name a tool that exists, or it is the model talking about JSON
    if names is not None and d['name'] not in set(names): return None
    return mk_tc(d['name'], tag_args(d))

# %% ../nbs/01_tags.ipynb #a097ff21
def parse_tool_tags_ex(text, names=None):
    "`(clean_text, calls, failed)`. `failed` marks a call the model emitted that nothing could parse."
    t = text or ''
    tcs, failed = parse_fn_tags(t), False   # the XML dialect is read FIRST: a value never decides the call
    rest = _toolcall_re.sub('', t)
    for b in _toolcall_re.findall(t):
        if parse_fn_tags(b): continue
        if (tc := mk_tag_tc(b)): tcs.append(tc)
        else: failed = True             # a block nothing could read is a loss, never a silent deletion
    if (k := rest.rfind('<tool_call>')) >= 0:   # an opener the model never closed: cut at the token cap
        b = rest[k + len('<tool_call>'):]
        if not parse_fn_tags(b):
            if (tc := mk_tag_tc(b)): tcs.append(tc)
            else: failed = True
        rest = rest[:k]
    if not tcs and not failed and (tc := lone_tag_tc(t, names)): return '', [tc], False
    clean = _fnblk_re.sub('', _toolres_re.sub('', rest)).strip('\n')
    return clean, tcs, failed

def parse_tool_tags(text, names=None):
    "Return clean text and calls parsed from `<tool_call>` and `<function=>` blocks."
    return parse_tool_tags_ex(text, names)[:2]

# %% ../nbs/01_tags.ipynb #530417a6
def tag_call_shape(text, names=None):
    "Does `text` still show a call the parser did not take? `names` limits it to tools that exist."
    t = text or ''
    if '<tool_call' in t: return True
    if not any(f'"{k}"' in t for k in TAG_ARG_KEYS): return False
    pat = '|'.join(re.escape(str(n)) for n in (names or []) if n) if names is not None else r'[A-Za-z_]\w*'
    return bool(pat) and bool(re.search(rf'"name"\s*:\s*"(?:{pat})"', t))

# %% ../nbs/01_tags.ipynb #150e47be
TAG_TOOLS_SP = """

# Tools

You can call the functions below. Their signatures are given as JSON schemas inside \
<tools></tools>:

<tools>
{tools}
</tools>

To call one, emit a JSON object with the function's name and its arguments inside \
<tool_call></tool_call>. Then end your reply immediately and wait:

<tool_call>
{{"name": "the_function_name", "arguments": {{"first": "value"}}}}
</tool_call>

Nothing may follow </tool_call> in the same message: not a comment, not a guess at what the \
result will be, not another call. Stop there. Call one function at a time.

Do not describe the call in prose as well as emitting it, and never invent a result -- the real \
one comes back in the next message, under a "## Tool result (name)" heading. That heading is the \
only form a result ever takes: do not write result markup of your own, do not wrap a result in \
tags, and do not copy a result back into your reply. Say what you concluded from it, not what \
it said."""

def tag_tools_sp(toolspecs, sp='', template=TAG_TOOLS_SP):
    "`sp` plus the tag protocol and `toolspecs` as JSON, for a transport that can't carry tools."
    if not toolspecs: return sp
    block = '\n'.join(json.dumps(t, ensure_ascii=False) for t in toolspecs)
    return (sp or '') + template.format(tools=block)

# %% ../nbs/01_tags.ipynb #38bb19e1
def RAW_DUMP():
    "Path a capture is writing to, from `$URAI_RAW_DUMP`, or None. Read per call, so a test can set it."
    return os.environ.get('URAI_RAW_DUMP') or None

def dump_raw(toolspecs, raw, path=None):
    "Append one `(tools, raw)` pair to the capture file, for replaying real traffic through the parser."
    if not (path := path or RAW_DUMP()) or not raw: return False
    with open(path, 'a') as f: f.write(json.dumps({'tools': toolspecs or [], 'raw': raw}) + '\n')
    return True


# %% ../nbs/01_tags.ipynb #dfb0657a
_tags = ('<think>', '</think>', '<tool_call>', '</tool_call>', '<function=', '</function>',
         *(f'<{n}>' for n in _res_tags), *(f'</{n}>' for n in _res_tags))

class StreamSplit:
    "Stateful splitter: `<think>` becomes thought chunks, tool blocks are held back and parsed."
    def __init__(self, keep_raw=None):
        self.buf, self.state, self.text, self.thought = '', 'text', '', ''
        self.tool_calls, self._tc_buf, self._strip = [], '', False
        self.failed, self._end = False, '</tool_call>'
        self.raw = '' if (RAW_DUMP() if keep_raw is None else keep_raw) else None

    def _held(self):
        "Length of the longest `buf` suffix that could still become a tag."
        for n in range(min(len(self.buf), max(map(len, _tags)) - 1), 0, -1):
            if any(t.startswith(self.buf[-n:]) for t in _tags): return n
        return 0

    def _emit_text(self, out):
        out = _toolres_re.sub('', out)       # invented result markup: the streamed path never
        if self._strip: out = out.lstrip('\n')   # reaches `parse_tool_tags`, so it is dropped here
        if not out: return None
        self._strip = False; self.text += out
        return {'content': [{'type': 'text', 'text': out}]}

    def _close_tool(self):
        "Run the buffered tool block through the same ladder the non-streaming path uses."
        buf, self._tc_buf = self._tc_buf, ''
        if (tcs := parse_fn_tags(buf)): self.tool_calls += tcs
        elif (tc := mk_tag_tc(buf)): self.tool_calls.append(tc)
        elif buf.strip(): self.failed = True

    def feed(self, s):
        "Consume a text delta and yield chunk dicts."
        if self.raw is not None: self.raw += s
        self.buf += s
        while True:
            if self.state == 'text':
                cands = [(k, t) for k, t in ((self.buf.find('<think>'), '<think>'),
                                             (self.buf.find('<tool_call>'), '<tool_call>'),
                                             (self.buf.find('<function='), '<function=')) if k >= 0]
                if not cands:
                    n = self._held()
                    out, self.buf = self.buf[:len(self.buf) - n], self.buf[len(self.buf) - n:]
                    if (c := self._emit_text(out)): yield c
                    return
                k, tag = min(cands)
                out, self.buf = self.buf[:k], self.buf[k + len(tag):]
                if tag == '<think>': self.state = 'think'
                else:
                    self.state, self._end = 'tool', '</tool_call>' if tag == '<tool_call>' else '</function>'
                    # the opener is part of the block the XML parser reads, so it goes in the buffer
                    self._tc_buf = '' if tag == '<tool_call>' else tag
                if (c := self._emit_text(out)): yield c
            elif self.state == 'think':
                k = self.buf.find('</think>')
                if k < 0:
                    n = self._held()
                    out, self.buf = self.buf[:len(self.buf) - n], self.buf[len(self.buf) - n:]
                    if out: self.thought += out; yield {'channels': {'thought': out}}
                    return
                out, self.buf, self.state, self._strip = self.buf[:k], self.buf[k + len('</think>'):], 'text', True
                if out: self.thought += out; yield {'channels': {'thought': out}}
            else:                                    # inside a tool call
                k = self.buf.find(self._end)
                if k < 0:
                    n = self._held()
                    self._tc_buf += self.buf[:len(self.buf) - n]; self.buf = self.buf[len(self.buf) - n:]
                    return
                self._tc_buf += self.buf[:k] + (self._end if self._end == '</function>' else '')
                self.buf, self.state, self._strip = self.buf[k + len(self._end):], 'text', True
                self._close_tool()

    def finish(self):
        "Flush leftovers: unterminated think becomes thought, an unclosed tool block is salvaged."
        s, self.buf = self.buf, ''
        if self.state == 'think':
            if s: self.thought += s; yield {'channels': {'thought': s}}
        elif self.state == 'tool':
            self._tc_buf += s
            self._close_tool()
        elif (c := self._emit_text(s)): yield c

# %% ../nbs/01_tags.ipynb #299c6b54
def acc_tc(acc, deltas):
    "Fold streamed OpenAI `tool_calls` deltas into `acc`, a list of partial tool_call dicts."
    for d in deltas or []:
        i = d.get('index', 0)
        while len(acc) <= i: acc.append({'id': None, 'type': 'function',
                                         'function': {'name': '', 'arguments': ''}})
        if d.get('id'): acc[i]['id'] = d['id']
        f = d.get('function') or {}
        if f.get('name'): acc[i]['function']['name'] += f['name']
        if f.get('arguments'): acc[i]['function']['arguments'] += f['arguments']
