"""Reading thinking and tool calls out of plain text.

Docs: https://vedicreader.github.io/urai/tags.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_tags.ipynb.

# %% auto #0
__all__ = ['TAG_ARG_KEYS', 'TAG_TOOLS_SP', 'split_think', 'tag_args', 'mk_tag_tc', 'lone_tag_tc', 'parse_tool_tags',
           'tag_call_shape', 'tag_tools_sp', 'StreamSplit', 'acc_tc']

# %% ../nbs/01_tags.ipynb #4b3a54bc
import json, re, uuid
from fastcore.all import L

# %% ../nbs/01_tags.ipynb #80122023
_think_re = re.compile(r'<think>(.*?)</think>', re.DOTALL)

def split_think(text):
    "Split `<think>...</think>` out of `text`, returning `(clean_text, thought)`."
    text = text or ''
    ths = [m.strip() for m in _think_re.findall(text)]
    text = _think_re.sub('', text)
    if '<think>' in text:            # unterminated, e.g. cut off at the token cap
        text, _, rest = text.partition('<think>')
        ths.append(rest.strip())
    return text.strip('\n'), '\n'.join(th for th in ths if th)

# %% ../nbs/01_tags.ipynb #c8c86dc2
TAG_ARG_KEYS = ('arguments', 'input', 'parameters')

def tag_args(d):
    "The argument dict of a tagged call, decoding the JSON string some models send instead."
    for k in TAG_ARG_KEYS:
        if (v := d.get(k)) is None: continue
        if isinstance(v, str):
            try: v = json.loads(v)
            except json.JSONDecodeError: continue
        if isinstance(v, dict): return v
    return {}

def mk_tag_tc(s):
    "A tool_call dict from the JSON inside a `<tool_call>` block, or None."
    try: d = json.loads(s)
    except (json.JSONDecodeError, TypeError): return None
    if not isinstance(d, dict) or not d.get('name'): return None
    return {'id': f'call_{uuid.uuid4().hex[:8]}', 'type': 'function',
            'function': {'name': d['name'], 'arguments': tag_args(d)}}

# %% ../nbs/01_tags.ipynb #894908ea
_res_tags = ('tool_result', 'tool_results', 'function_result', 'function_results',
             'tool_function_result', 'tool_function_results',
             'tool_function_call', 'tool_function_calls',
             'function_call', 'function_calls', 'tool_use')
_toolres_re = re.compile('|'.join(rf'</?{t}>>?' for t in _res_tags) + r'|</?tool_call>', re.I)
_toolcall_re = re.compile(r'<tool_call>\s*(.*?)\s*</tool_call>', re.DOTALL)
_fence_re = re.compile(r'^```(?:json)?\s*|\s*```$')

def lone_tag_tc(text):
    "A whole reply that is one bare call object: what the tags asked for, without the tags."
    s = _fence_re.sub('', (text or '').strip()).strip()
    if not (s.startswith('{') and s.endswith('}')): return None
    try: d = json.loads(s)
    except json.JSONDecodeError: return None
    if not isinstance(d, dict) or not d.get('name'): return None
    if not any(k in d for k in TAG_ARG_KEYS): return None
    return mk_tag_tc(s)

# %% ../nbs/01_tags.ipynb #32403bf7
def parse_tool_tags(text):
    "Parse Hermes and Qwen style `<tool_call>{json}</tool_call>` blocks, returning `(clean_text, tool_calls)`."
    tcs = [tc for m in _toolcall_re.findall(text or '') if (tc := mk_tag_tc(m))]
    if not tcs and (tc := lone_tag_tc(text)): return '', [tc]
    return _toolres_re.sub('', _toolcall_re.sub('', text or '')).strip('\n'), tcs

# %% ../nbs/01_tags.ipynb #8f792963
def tag_call_shape(text, names=None):
    "Does `text` still show a call the parser did not take? `names` limits it to tools that exist."
    t = text or ''
    if '<tool_call' in t: return True
    if not any(f'"{k}"' in t for k in TAG_ARG_KEYS): return False
    pat = '|'.join(re.escape(str(n)) for n in (names or []) if n) if names is not None else r'[A-Za-z_]\w*'
    return bool(pat) and bool(re.search(rf'"name"\s*:\s*"(?:{pat})"', t))

# %% ../nbs/01_tags.ipynb #f5307118
TAG_TOOLS_SP = """

# Tools

You can call the functions below. Their signatures are given as JSON schemas inside \
<tools></tools>:

<tools>
{tools}
</tools>

To call one, emit a JSON object with the function's name and its arguments inside \
<tool_call></tool_call>. Then end your reply immediately and wait:

<tool_call>
{{"name": "the_function_name", "arguments": {{"first": "value"}}}}
</tool_call>

Nothing may follow </tool_call> in the same message: not a comment, not a guess at what the \
result will be, not another call. Stop there. Call one function at a time.

Do not describe the call in prose as well as emitting it, and never invent a result -- the real \
one comes back in the next message, under a "## Tool result (name)" heading. That heading is the \
only form a result ever takes: do not write result markup of your own, do not wrap a result in \
tags, and do not copy a result back into your reply. Say what you concluded from it, not what \
it said."""

def tag_tools_sp(toolspecs, sp='', template=TAG_TOOLS_SP):
    "`sp` plus the tag protocol and `toolspecs` as JSON, for a transport that can't carry tools."
    if not toolspecs: return sp
    block = '\n'.join(json.dumps(t, ensure_ascii=False) for t in toolspecs)
    return (sp or '') + template.format(tools=block)

# %% ../nbs/01_tags.ipynb #6d388016
_tags = ('<think>', '</think>', '<tool_call>', '</tool_call>',
         *(f'<{n}>' for n in _res_tags), *(f'</{n}>' for n in _res_tags))

class StreamSplit:
    "Stateful splitter: `<think>` becomes thought chunks, `<tool_call>` blocks are held back and parsed."
    def __init__(self):
        self.buf, self.state, self.text, self.thought = '', 'text', '', ''
        self.tool_calls, self._tc_buf, self._strip = [], '', False

    def _held(self):
        "Length of the longest `buf` suffix that could still become a tag."
        for n in range(min(len(self.buf), max(map(len, _tags)) - 1), 0, -1):
            if any(t.startswith(self.buf[-n:]) for t in _tags): return n
        return 0

    def _emit_text(self, out):
        out = _toolres_re.sub('', out)       # invented result markup: the streamed path never
        if self._strip: out = out.lstrip('\n')   # reaches `parse_tool_tags`, so it is dropped here
        if not out: return None
        self._strip = False; self.text += out
        return {'content': [{'type': 'text', 'text': out}]}

    def feed(self, s):
        "Consume a text delta and yield chunk dicts."
        self.buf += s
        while True:
            if self.state == 'text':
                cands = [(k, t, st) for k, t, st in ((self.buf.find('<think>'), '<think>', 'think'),
                                                     (self.buf.find('<tool_call>'), '<tool_call>', 'tool')) if k >= 0]
                if not cands:
                    n = self._held()
                    out, self.buf = self.buf[:len(self.buf) - n], self.buf[len(self.buf) - n:]
                    if (c := self._emit_text(out)): yield c
                    return
                k, tag, st = min(cands)
                out, self.buf, self.state = self.buf[:k], self.buf[k + len(tag):], st
                if (c := self._emit_text(out)): yield c
            elif self.state == 'think':
                k = self.buf.find('</think>')
                if k < 0:
                    n = self._held()
                    out, self.buf = self.buf[:len(self.buf) - n], self.buf[len(self.buf) - n:]
                    if out: self.thought += out; yield {'channels': {'thought': out}}
                    return
                out, self.buf, self.state, self._strip = self.buf[:k], self.buf[k + len('</think>'):], 'text', True
                if out: self.thought += out; yield {'channels': {'thought': out}}
            else:                                    # inside a tool call
                k = self.buf.find('</tool_call>')
                if k < 0:
                    n = self._held()
                    self._tc_buf += self.buf[:len(self.buf) - n]; self.buf = self.buf[len(self.buf) - n:]
                    return
                self._tc_buf += self.buf[:k]
                self.buf, self.state, self._strip = self.buf[k + len('</tool_call>'):], 'text', True
                if (tc := mk_tag_tc(self._tc_buf)): self.tool_calls.append(tc)
                self._tc_buf = ''

    def finish(self):
        "Flush leftovers: unterminated think becomes thought, an unclosed tool block is parsed if it can be."
        s, self.buf = self.buf, ''
        if self.state == 'think':
            if s: self.thought += s; yield {'channels': {'thought': s}}
        elif self.state == 'tool':
            if (tc := mk_tag_tc(self._tc_buf + s)): self.tool_calls.append(tc)
            self._tc_buf = ''
        elif (c := self._emit_text(s)): yield c

# %% ../nbs/01_tags.ipynb #1eb4c797
def acc_tc(acc, deltas):
    "Fold streamed OpenAI `tool_calls` deltas into `acc`, a list of partial tool_call dicts."
    for d in deltas or []:
        i = d.get('index', 0)
        while len(acc) <= i: acc.append({'id': None, 'type': 'function',
                                         'function': {'name': '', 'arguments': ''}})
        if d.get('id'): acc[i]['id'] = d['id']
        f = d.get('function') or {}
        if f.get('name'): acc[i]['function']['name'] += f['name']
        if f.get('arguments'): acc[i]['function']['arguments'] += f['arguments']
